import type { Lesson } from "../../../types/lesson";
import {
  SOUND_U6,
  IMG46,
  chorePhotoMatch,
  choreMatchPhrases,
  peopleJobs,
  collocationGaps,
  albertBellaJobs,
  listenQuestionGaps,
  doesGrammarGaps,
  chloeDialogueChoices,
  questionPrompts,
  houseworkSpeakPrompts,
  choreR4Transcript,
  albertBellaR5Transcript,
  doesR6Transcript,
  VIDEO_ID,
  videoQuiz,
} from "./activities";
import { lesson46Homework } from "./homework";
import { choreFlashcards } from "./vocabulary";

export const lesson46: Lesson = {
  id: "46",
  number: 46,
  title: "Jobs around the house",
  level: "A1",
  moduleId: "a1-present",
  order: 46,
  status: "published",
  estimatedMinutes: 65,
  hasHomework: true,
  topic: "housework · Present Simple questions Does he/she…?",
  description:
    "Match housework phrases to pictures, listen about Albert and Bella, then ask Does he/she…? questions with your teacher.",
  chips: ["clean / cook / wash", "Does he…?", "Yes, she does."],
  route: "/lessons/46",
  legacyRoute: "/lesson-46",
  prevLessonPath: "/lessons/45",
  nextLessonPath: "/lessons/47",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 45", path: "/lessons/45", ghost: true },
    { label: "HW46 →", path: "/hw-46", ghost: true },
  ],
  homework: lesson46Homework,
  flow: [
    { href: "#l46-intro", label: "Intro" },
    { href: "#l46-vocab", label: "Vocab" },
    { href: "#l46-the-tip", label: "Порада" },
    { href: "#l46-match", label: "1 Match" },
    { href: "#l46-audio-r4", label: "1b Listen" },
    { href: "#l46-people", label: "2 People" },
    { href: "#l46-collocations", label: "3 Phrases" },
    { href: "#l46-audio-r5", label: "4a Listen" },
    { href: "#l46-albert-bella", label: "4a Who?" },
    { href: "#l46-questions", label: "4b Questions" },
    { href: "#l46-grammar", label: "5 Grammar" },
    { href: "#l46-audio-r6", label: "6 Sound" },
    { href: "#l46-dialogue", label: "7 Dialogue" },
    { href: "#l46-order", label: "8a Order" },
    { href: "#l46-speak", label: "8b Speak" },
    { href: "#l46-exit", label: "Exit" },
    { href: "#l46-video", label: "Video" },
    { href: "#l46-video-quiz", label: "Video quiz" },
  ],
  sections: [
    {
      type: "text",
      id: "l46-intro",
      title: "Jobs around the house",
      description: "Goal: ask and answer about things people often do.",
      body: "Today we learn housework phrases and Present Simple questions with he / she / it: Does she clean the bathroom? Yes, she does.",
      bullets: [
        "Grammar: Does he/she…? · Yes, he does. / No, she doesn’t.",
        "Vocabulary: clean, cook, feed, wash, walk the dog, do the washing…",
      ],
    },
    {
      type: "custom",
      id: "l46-vocab",
      kicker: "Vocabulary",
      title: "Housework phrases",
      description: "Tap: Ukrainian → English.",
      componentKey: "vocab-flip",
      props: {
        cards: choreFlashcards,
      },
    },
    {
      type: "text",
      id: "l46-the-tip",
      kicker: "Порада",
      title: "the чи a?",
      description: "Чому в домашніх справах часто the.",
      body: "У домашніх справах часто кажемо the, бо це звичайна / конкретна річ у домі (the bed — ліжко, на якому спиш; the dishes — посуд після вечері). a — якийсь / один / неконкретний. the — обидва знають, про що мова (наша собака, цей посуд). Деякі фрази фіксовані з the: make the bed, do the laundry, take out the rubbish.",
      bullets: [
        "make the bed (твоє ліжко вдома) · buy a bed (якесь ліжко в магазині)",
        "feed the dog (наша собака) · I saw a dog (якась собака)",
        "wash the dishes · wash a plate",
      ],
    },
    {
      type: "custom",
      id: "l46-match",
      kicker: "1a",
      title: "Match the pictures and the phrases",
      description: "Choose the phrase for each picture A–H.",
      componentKey: "photo-sentence-match",
      props: {
        options: choreMatchPhrases.map((s) => ({ ...s })),
        images: chorePhotoMatch.map((p) => ({
          id: p.id,
          src: IMG46(p.file),
          alt: p.alt,
          answer: p.answer,
        })),
      },
    },
    {
      type: "custom",
      id: "l46-audio-r4",
      kicker: "1b · 6.4",
      title: "Listen and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(4),
        trackLabel: "6.4",
        title: "Jobs around the house",
        exercise: "1b",
        transcriptLines: [...choreR4Transcript],
      },
    },
    {
      type: "custom",
      id: "l46-people",
      kicker: "2",
      title: "Jobs each person does",
      description:
        "Look at the pictures again. Say sentences about Thomas, Masaru, Isabella and Milada. Use he / she + -s.",
      componentKey: "photo-gallery",
      props: {
        compact: true,
        images: peopleJobs.map((p) => ({
          id: p.id,
          src: IMG46(p.file),
          alt: `${p.name}`,
          caption: p.name,
          fit: "contain" as const,
        })),
      },
    },
    {
      type: "speakingPrompt",
      id: "l46-people-speak",
      kicker: "2 · Speak",
      title: "Say the sentences aloud",
      description:
        "Look at the pictures. Tell your teacher what each person does. Use he / she + -s.",
      prompts: peopleJobs.map((p) => `${p.name}: …`),
      note: "Example: Thomas cleans the bathroom and…",
    },
    {
      type: "fillBlank",
      id: "l46-collocations",
      kicker: "3",
      title: "Complete the phrases",
      description: "Use verbs from Exercise 1a: clean, cook, feed, wash.",
      items: collocationGaps.map((g) => ({
        id: g.id,
        before: g.before || "___",
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "custom",
      id: "l46-audio-r5",
      kicker: "4a · 6.5",
      title: "Listen · Albert and Bella",
      description:
        "Listen to the conversation. Who does the jobs around the house?",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(5),
        trackLabel: "6.5",
        title: "Albert and Bella · housework",
        exercise: "4a",
        transcriptLines: [...albertBellaR5Transcript],
      },
    },
    {
      type: "multipleChoiceGroup",
      id: "l46-albert-bella",
      kicker: "4a",
      title: "Who does the jobs?",
      description: "Choose Albert or Bella for each job.",
      items: albertBellaJobs.map((item) => ({
        id: item.id,
        prompt: item.prompt,
        options: [...item.options],
        correctAnswer: item.correctAnswer,
      })),
    },
    {
      type: "fillBlank",
      id: "l46-questions",
      kicker: "4b",
      title: "Complete the questions",
      description: "Listen again if you need to. Write Do or does.",
      items: listenQuestionGaps.map((g) => ({
        id: g.id,
        before: g.before ? `${g.before} ` : "",
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "fillBlank",
      id: "l46-grammar",
      kicker: "5",
      title: "Present simple questions: he / she / it",
      description:
        "Complete the grammar box. Use Does / does / doesn’t. + Yes, she does. − No, she doesn’t. Wh- + does + he/she + verb…?",
      items: doesGrammarGaps.map((g) => ({
        id: g.id,
        before: g.before ? `${g.before} ` : "",
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "custom",
      id: "l46-audio-r6",
      kicker: "6 · 6.6",
      title: "Pronunciation · does",
      description:
        "Listen and notice does in questions and short answers. Then repeat with your teacher.",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(6),
        trackLabel: "6.6",
        title: "does · strong and weak",
        exercise: "6",
        transcriptLines: [...doesR6Transcript],
      },
    },
    {
      type: "custom",
      id: "l46-dialogue",
      kicker: "7",
      title: "Nicholas and Chloe · choose the correct form",
      description:
        "Chloe talks about her dog, Ronaldo. Tap the correct word in each line.",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "Present simple · do / does + verb",
        examples: [
          {
            id: "e1",
            text: "Do you *walk* him every day?",
          },
          {
            id: "e2",
            text: "My dad usually *walks* him.",
          },
        ],
        choices: chloeDialogueChoices.map((c) => ({ ...c })),
      },
    },
    {
      type: "wordOrder",
      id: "l46-order",
      kicker: "8a",
      title: "Make questions",
      description: "Put the words in order. Use do / does where you need them.",
      items: questionPrompts.map((item) => ({
        scramble: item.scramble,
        parts: [...item.parts],
        answer: item.answer,
      })),
    },
    {
      type: "speakingPrompt",
      id: "l46-speak",
      kicker: "8b · Speak",
      title: "Ask and answer with your teacher",
      description:
        "Use the questions from 8a about a friend or family member. Take turns with your teacher.",
      prompts: [...houseworkSpeakPrompts],
      note: "Model: Does your friend live in a flat? — Yes, he does. Who does he live with? — He lives with his parents.",
    },
    {
      type: "text",
      id: "l46-exit",
      kicker: "Exit",
      title: "Today you can…",
      body: "name jobs around the house; ask Does he/she…?; answer Yes, he does. / No, she doesn’t.",
      bullets: [
        "Does she clean the bathroom? — Yes, she does.",
        "What jobs does he do around the house?",
        "Bella cooks dinner. Albert walks the dog.",
      ],
    },
    {
      type: "custom",
      id: "l46-video",
      kicker: "Extra · Video",
      title: "Third person singular · he / she",
      description:
        "Watch the video with your teacher. Four short conversations use he / she + -s.",
      componentKey: "youtube-video",
      props: {
        videoId: VIDEO_ID,
        iframeTitle: "Lesson six — third person singular (he / she)",
      },
    },
    {
      type: "multipleChoiceGroup",
      id: "l46-video-quiz",
      kicker: "Extra · Video quiz",
      title: "Answer from the video",
      description: "Listen again and choose the correct answer.",
      items: videoQuiz.map((q) => ({
        id: q.id,
        prompt: q.prompt,
        options: [...q.options],
        correctAnswer: q.correctAnswer,
      })),
    },
    {
      type: "homeworkLink",
      id: "l46-hw",
      title: "Homework",
      path: "/hw-46",
      label: "HW46 →",
      summary: "UA→EN cards · picture cards · Does…? gaps · write",
    },
  ],
};
