import type { Lesson } from "../../../types/lesson";
import {
  dayWarmUpPrompts,
  doDoesDrill,
  shortAnswerGaps,
  scheduleBuildPrompts,
  frequencySpeakPrompts,
  frequencySpeakModels,
  beFreqChoices,
  colleagueAskYou,
  youAskTeacher,
  mariaWeekText,
  mariaQuiz,
  weekFinalPrompts,
  weekFinalModels,
  scenarioTownPrompts,
  scenarioTownModels,
  scenarioFriendPrompts,
  scenarioFriendModels,
  scenarioCafePrompts,
  scenarioCafeModels,
  scenarioHomePrompts,
  scenarioHomeModels,
} from "./activities";
import { lesson48Homework } from "./homework";
import { lesson48TeacherScript } from "./teacherScript";
import { weekFlashcards } from "./vocabulary";

export const lesson48: Lesson = {
  id: "48",
  number: 48,
  title: "Review · My week",
  level: "A1",
  moduleId: "a1-present",
  order: 48,
  status: "published",
  estimatedMinutes: 60,
  hasHomework: true,
  topic: "My week · Present Simple · do/does · frequency · work schedule",
  description:
    "Speaking project: build your real week, ask and answer about schedules, then tell your week in 8–10 sentences.",
  chips: ["Do you…?", "Does he…?", "I usually…", "from… to…"],
  route: "/lessons/48",
  legacyRoute: "/lesson-48",
  prevLessonPath: "/lessons/47",
  nextLessonPath: "/lessons/49",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 47", path: "/lessons/47", ghost: true },
    { label: "HW48 →", path: "/hw-48", ghost: true },
  ],
  homework: lesson48Homework,
  flow: [
    { href: "#l48-teacher", label: "Сценарій", teacherOnly: true },
    { href: "#l48-intro", label: "Goal" },
    { href: "#l48-chunks", label: "Chunks" },
    { href: "#l48-warm", label: "Days" },
    { href: "#l48-does", label: "Do/Does" },
    { href: "#l48-schedule", label: "Schedule" },
    { href: "#l48-freq", label: "Usually" },
    { href: "#l48-be-freq", label: "be + often" },
    { href: "#l48-role", label: "Colleague" },
    { href: "#l48-ask", label: "Ask me" },
    { href: "#l48-maria", label: "Maria" },
    { href: "#l48-quiz", label: "Check" },
    { href: "#l48-final", label: "My week" },
    { href: "#l48-sc-town", label: "Town" },
    { href: "#l48-sc-friend", label: "Friend" },
    { href: "#l48-sc-cafe", label: "Café" },
    { href: "#l48-sc-home", label: "Home" },
    { href: "#l48-exit", label: "Exit" },
  ],
  sections: [
    {
      type: "custom",
      id: "l48-teacher",
      teacherOnly: true,
      kicker: "Тільки для вчителя",
      title: "Сценарій уроку",
      description:
        "Видно лише з учительного акаунта (VITE_TEACHER_EMAIL). Учень цей блок не бачить.",
      componentKey: "teacher-script",
      props: {
        heading: lesson48TeacherScript.heading,
        goal: lesson48TeacherScript.goal,
        blocks: lesson48TeacherScript.blocks.map((b) => ({
          time: b.time,
          title: b.title,
          lines: [...b.lines],
        })),
        tips: [...lesson48TeacherScript.tips],
        homework: [...lesson48TeacherScript.homework],
      },
    },
    {
      type: "text",
      id: "l48-intro",
      title: "My week · speaking project",
      description: "One clear goal. ~70% speaking.",
      body: "Today you build your real week in Present Simple. No Past Simple. No long new vocabulary. No phonetics block.",
      bullets: [
        "Tell your week in 8–10 sentences (no cards at the end).",
        "Ask your teacher 3–4 questions about her week.",
        "Focus: do/does · he/she + -s · on/in/at · at work / go to work / go home.",
      ],
    },
    {
      type: "custom",
      id: "l48-chunks",
      kicker: "0–2 · Chunks",
      title: "Week language",
      description: "Tap UA → EN. Keep these ready for speaking.",
      componentKey: "vocab-flip",
      props: { cards: weekFlashcards },
    },
    {
      type: "speakingPrompt",
      id: "l48-warm",
      kicker: "0–7 · Warm-up",
      title: "Your week · day by day",
      description:
        "Not “Tell me about your week” yet. Answer one question at a time. Teacher writes keywords only.",
      prompts: [...dayWarmUpPrompts],
      note: "Days: Mon–Sun. After 3–4 answers: “Good. Now we are making your real weekly schedule.”",
    },
    {
      type: "custom",
      id: "l48-does",
      kicker: "7–15 · Quick drill",
      title: "Do / Does…?",
      description:
        "Make the question. After does → base verb. Then short answers: Yes, I do. / No, he doesn’t.",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "you → Do · he/she → Does",
        examples: [
          { id: "e1", text: "*Do* you work?" },
          { id: "e2", text: "*Does* he work?" },
        ],
        choices: [
          ...doDoesDrill.map((d) => ({
            id: d.id,
            before: `${d.cue} → `,
            after: "",
            options: [...d.options],
            answer: d.answer,
          })),
          ...shortAnswerGaps.map((g) => ({
            id: g.id,
            before: g.before ? `${g.before} ` : "",
            after: g.after,
            options: [...g.options],
            answer: g.answers[0],
          })),
        ],
      },
    },
    {
      type: "speakingPrompt",
      id: "l48-schedule",
      kicker: "15–25 · Build",
      title: "Build your weekly schedule",
      description:
        "Teacher table: Day · Work/day off · Time · Activity. You say short facts. Teacher writes keywords — not full sentences for you.",
      prompts: [...scheduleBuildPrompts],
      note: "Real week: barbershop days, days off, start/finish times, evening habits.",
    },
    {
      type: "speakingPrompt",
      id: "l48-freq",
      kicker: "25–35 · Frequency",
      title: "Five true sentences",
      description:
        "Cards: always · usually · often · sometimes · never. Make five true sentences about your week.",
      prompts: [...frequencySpeakPrompts],
      models: [...frequencySpeakModels],
      hideModels: true,
      note: "Tap Підказка only if stuck. Prefer your truth.",
    },
    {
      type: "custom",
      id: "l48-be-freq",
      kicker: "be + frequency",
      title: "I often work · I am often tired",
      description: "With normal verbs: adverb before the verb. With be: after am/is/are.",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "usually / often · verb vs be",
        examples: [
          { id: "e1", text: "I *often* work." },
          { id: "e2", text: "I am *often* tired." },
        ],
        choices: beFreqChoices.map((c) => ({
          id: c.id,
          before: c.before,
          after: c.after,
          options: [...c.options],
          answer: c.answer,
        })),
      },
    },
    {
      type: "speakingPrompt",
      id: "l48-role",
      kicker: "35–45 · Role-play",
      title: "New colleague asks you",
      description:
        "Teacher: “I am your new colleague. I want to know your schedule.” Answer. Then swap roles.",
      prompts: [...colleagueAskYou],
      note: "Short answers OK: Yes, I do. / No, I don’t. / From Tuesday to Thursday.",
    },
    {
      type: "speakingPrompt",
      id: "l48-ask",
      kicker: "35–45 · Your turn",
      title: "Ask your teacher (min. 3)",
      description: "You ask. Teacher answers. Minimum three questions.",
      prompts: [...youAskTeacher],
      note: "Must ask at least 3. More is better.",
    },
    {
      type: "text",
      id: "l48-maria",
      kicker: "45–52 · Reading",
      title: "Someone else’s week · Maria",
      description: "Very short text. Then answer the quiz.",
      body: mariaWeekText.join(" "),
      bullets: [
        "Tell your teacher one difference: your week vs Maria’s week.",
      ],
    },
    {
      type: "multipleChoiceGroup",
      id: "l48-quiz",
      kicker: "45–52 · Check",
      title: "Maria · questions",
      description: "Choose the correct answer.",
      items: mariaQuiz.map((q) => ({
        id: q.id,
        prompt: q.prompt,
        options: [...q.options],
        correctAnswer: q.correctAnswer,
      })),
    },
    {
      type: "speakingPrompt",
      id: "l48-final",
      kicker: "52–60 · Final output",
      title: "My week · 8–10 sentences",
      description:
        "Hide the schedule table (or keep only day names). Speak without full model sentences.",
      prompts: [...weekFinalPrompts],
      models: [...weekFinalModels],
      hideModels: true,
      note: "Delayed correction only on 3 things: he/she + -s · on/in/at · do/does.",
    },
    {
      type: "text",
      id: "l48-sc-intro",
      kicker: "Extra · Speaking scenarios",
      title: "Practice L30–47 with your teacher",
      description: "Pick 1–2 scenarios (about 5 minutes each). Present Simple only — no Past story here.",
      body: "Recycle: there is/are · town · have got · describing people · can/can’t · food habits · café · housework · Does…?",
      bullets: [
        "Teacher and student take turns.",
        "Use short answers: Yes, I do. / No, I don’t. / Yes, there is. / Yes, I can.",
      ],
    },
    {
      type: "speakingPrompt",
      id: "l48-sc-town",
      kicker: "Scenario A · Town (L31–35)",
      title: "My town · Is there…?",
      description:
        "Places in town, there is/are, and very simple directions. Ask and answer with your teacher.",
      prompts: [...scenarioTownPrompts],
      models: [...scenarioTownModels],
      hideModels: true,
      note: "L31–35 recycle. Keep directions short.",
    },
    {
      type: "speakingPrompt",
      id: "l48-sc-friend",
      kicker: "Scenario B · Friend / bag (L38–39, L47)",
      title: "Have you got…? · Can you…?",
      description:
        "Describe a person, talk about your bag, and ask one can/can’t question.",
      prompts: [...scenarioFriendPrompts],
      models: [...scenarioFriendModels],
      hideModels: true,
      note: "L38–39 + light L47. Short answers: Yes, I have. / No, I haven’t. / Yes, I can.",
    },
    {
      type: "speakingPrompt",
      id: "l48-sc-cafe",
      kicker: "Scenario C · Café (L44–45)",
      title: "Food habits · order in a café",
      description:
        "Habits with usually/never, then a short café role-play with your teacher.",
      prompts: [...scenarioCafePrompts],
      models: [...scenarioCafeModels],
      hideModels: true,
      note: "L44–45. Swap roles: customer ↔ waiter.",
    },
    {
      type: "speakingPrompt",
      id: "l48-sc-home",
      kicker: "Scenario D · Home (L45–46)",
      title: "Housework · Does he/she…?",
      description:
        "Home jobs, Does…? questions, and one mini contrast: every Saturday vs now.",
      prompts: [...scenarioHomePrompts],
      models: [...scenarioHomeModels],
      hideModels: true,
      note: "L45–46. One verb for PS vs PC only.",
    },
    {
      type: "text",
      id: "l48-exit",
      kicker: "Exit",
      title: "Now I can talk about my week.",
      body: "You built a real schedule, answered a colleague, asked questions, and told your week.",
      bullets: [
        "I work from … to … · I work at …",
        "I usually… · I often… · At the weekend, I…",
        "Do you…? / Does he…? — Yes, I do. / No, he doesn’t.",
      ],
    },
    {
      type: "homeworkLink",
      id: "l48-hw",
      title: "Homework",
      path: "/hw-48",
      label: "HW48 →",
      summary: "Schedule · 8 sentences · voice 40–60s · 4 questions",
    },
  ],
};
