import type { Lesson } from "../../../types/lesson";
import {
  SOUND_U6,
  IMG45,
  habitPhotoMatch,
  habitMatchSentences,
  timeExprGaps,
  timeExpressions,
  ericaText,
  tinaText,
  iToSheGaps,
  heSheGrammarExamples,
  heSheGaps,
  endingSoundItems,
  habitSpeakPrompts,
} from "./activities";
import { lesson45Homework } from "./homework";
import { timeFlashcards } from "./vocabulary";

export const lesson45: Lesson = {
  id: "45",
  number: 45,
  title: "Good and bad habits",
  level: "A1",
  moduleId: "a1-present",
  order: 45,
  status: "published",
  estimatedMinutes: 60,
  hasHomework: true,
  topic: "habits · time expressions · Present Simple he/she/it",
  description:
    "Match time expressions to pictures, read about Erica and Tina, then talk about another person’s good and bad habits with he/she + -s.",
  chips: ["in the morning", "he/she + -s", "doesn't + verb"],
  route: "/lessons/45",
  legacyRoute: "/lesson-45",
  prevLessonPath: "/lessons/44",
  nextLessonPath: "/lessons",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 44", path: "/lessons/44", ghost: true },
    { label: "HW45 →", path: "/hw-45", ghost: true },
  ],
  homework: lesson45Homework,
  flow: [
    { href: "#l45-intro", label: "Intro" },
    { href: "#l45-time-cards", label: "Time words" },
    { href: "#l45-match", label: "1 Match" },
    { href: "#l45-audio-r1", label: "1b Listen" },
    { href: "#l45-time-gaps", label: "3 You" },
    { href: "#l45-read-photos", label: "4 Photos" },
    { href: "#l45-read-tina", label: "4 Tina" },
    { href: "#l45-read-erica", label: "4 Erica" },
    { href: "#l45-habit-def", label: "4b Habit" },
    { href: "#l45-ito-she", label: "5 She" },
    { href: "#l45-grammar", label: "6 Grammar" },
    { href: "#l45-audio-r2", label: "7a Listen" },
    { href: "#l45-sounds", label: "7 Sounds" },
    { href: "#l45-gaps", label: "8 Gaps" },
    { href: "#l45-prepare", label: "9 Notes" },
    { href: "#l45-speak", label: "10 Speak" },
    { href: "#l45-exit", label: "Exit" },
  ],
  sections: [
    {
      type: "text",
      id: "l45-intro",
      title: "Good and bad habits",
      description: "Goal: talk about another person’s habits.",
      body: "Today we practise time expressions (in the morning, every day, at the weekend…) and Present Simple with he / she / it: She walks. She doesn’t take the bus.",
    },
    {
      type: "custom",
      id: "l45-time-cards",
      kicker: "Vocabulary",
      title: "Time expressions",
      description: "Tap: Ukrainian → English.",
      componentKey: "vocab-flip",
      props: {
        cards: timeFlashcards,
      },
    },
    {
      type: "custom",
      id: "l45-match",
      kicker: "1a",
      title: "Match the pictures and the sentences",
      description:
        "Choose the sentence for each picture. Look at the time words in bold in your head: in the morning, every day, in the evening…",
      componentKey: "photo-sentence-match",
      props: {
        options: habitMatchSentences.map((s) => ({ ...s })),
        images: habitPhotoMatch.map((p) => ({
          id: p.id,
          src: IMG45(p.file),
          alt: p.alt,
          answer: p.answer,
        })),
      },
    },
    {
      type: "custom",
      id: "l45-audio-r1",
      kicker: "1b · 6.1",
      title: "Listen and check",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(1),
        trackLabel: "6.1",
        title: "Time expressions · habits",
        exercise: "1b",
      },
    },
    {
      type: "fillBlank",
      id: "l45-time-gaps",
      kicker: "3",
      title: "Complete the sentences",
      description: `Use a time expression: ${timeExpressions.join(" · ")}. Answers can be true for you.`,
      items: timeExprGaps.map((g) => ({
        id: g.id,
        before: g.before,
        after: g.after,
        correctAnswers: [...g.answers],
        options: [...timeExpressions],
      })),
    },
    {
      type: "custom",
      id: "l45-read-photos",
      kicker: "4a",
      title: "Two friends",
      description: "Look at the photos. Who has good habits? Who has bad habits?",
      componentKey: "photo-gallery",
      props: {
        images: [
          {
            id: "tina",
            src: IMG45("tina-tv.png"),
            alt: "A woman watches TV and eats popcorn",
            caption: "A · Tina",
            fit: "contain",
          },
          {
            id: "erica",
            src: IMG45("erica-cycle.png"),
            alt: "A woman cycles to work",
            caption: "B · Erica",
            fit: "contain",
          },
        ],
      },
    },
    {
      type: "text",
      id: "l45-read-tina",
      kicker: "4a · A",
      title: "Tina",
      body: tinaText,
    },
    {
      type: "text",
      id: "l45-read-erica",
      kicker: "4a · B",
      title: "Erica",
      body: ericaText,
    },
    {
      type: "multipleChoice",
      id: "l45-habit-def",
      kicker: "4b",
      title: "What is a habit?",
      prompt: "A habit is…",
      options: [
        "something people often do",
        "something people never do",
      ],
      correctAnswer: "something people often do",
    },
    {
      type: "fillBlank",
      id: "l45-ito-she",
      kicker: "5",
      title: "I → she",
      description:
        "Change the sentences to she. Remember: she walks / she doesn’t take…",
      items: iToSheGaps.map((g) => ({
        id: g.id,
        before: g.before,
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "custom",
      id: "l45-grammar",
      kicker: "6",
      title: "Present Simple · he / she / it",
      description:
        "Most verbs: add -s (arrives). study → studies. watch / go / finish → watches / goes / finishes. Negative: doesn’t + base verb.",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "Present simple · he / she / it",
        examples: heSheGrammarExamples.map((e) => ({ ...e })),
        choices: [
          {
            id: "c1",
            before: "With he / she / it we usually add",
            after: "to the verb.",
            options: ["-s / -es", "-ing"],
            answer: "-s / -es",
          },
          {
            id: "c2",
            before: "Negative:",
            after: "+ base verb (doesn't walk).",
            options: ["doesn't", "don't"],
            answer: "doesn't",
          },
          {
            id: "c3",
            before: "study →",
            after: "",
            options: ["studies", "studys"],
            answer: "studies",
          },
          {
            id: "c4",
            before: "watch →",
            after: "",
            options: ["watches", "watchs"],
            answer: "watches",
          },
        ],
      },
    },
    {
      type: "custom",
      id: "l45-audio-r2",
      kicker: "7a · 6.2",
      title: "Listen to the -s endings",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(2),
        trackLabel: "6.2",
        title: "Verb endings /s/ /z/ /ɪz/",
        exercise: "7a",
      },
    },
    {
      type: "multipleChoiceGroup",
      id: "l45-sounds",
      kicker: "7",
      title: "Which sound: /s/, /z/ or /ɪz/?",
      description: "Choose the ending sound for each verb.",
      items: endingSoundItems.map((item) => ({
        id: item.id,
        prompt: item.prompt,
        options: [...item.options],
        correctAnswer: item.answer,
      })),
    },
    {
      type: "fillBlank",
      id: "l45-gaps",
      kicker: "8",
      title: "Complete with the correct form",
      description:
        "Write the verb in Present Simple (he/she). Use doesn’t + verb when you need a negative.",
      items: heSheGaps.map((g) => ({
        id: g.id,
        before: g.before,
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "custom",
      id: "l45-prepare",
      kicker: "9",
      title: "Prepare · notes about a friend",
      description:
        "Write notes about one friend or family member: good habits and bad habits.",
      componentKey: "write-lists",
      props: {
        lists: [
          {
            id: "good",
            label: "Good habits",
            placeholder: "She walks to work. She drinks water…",
          },
          {
            id: "bad",
            label: "Bad habits",
            placeholder: "He watches TV every night. He never studies…",
          },
        ],
      },
    },
    {
      type: "speakingPrompt",
      id: "l45-speak",
      kicker: "10",
      title: "Speak to your teacher",
      description: "Use your notes. Say he / she + -s and doesn’t + verb.",
      prompts: [...habitSpeakPrompts],
      note: "Model: My friend Petro walks to work. He doesn’t drink coffee. He always watches TV in the evening.",
    },
    {
      type: "text",
      id: "l45-exit",
      kicker: "Exit",
      title: "Today you can…",
      body: "use time expressions; say what another person does / doesn’t do; talk about good and bad habits.",
      bullets: [
        "She goes to the gym every day.",
        "He doesn’t take the bus.",
        "They watch TV in the evening. → He watches TV in the evening.",
      ],
    },
    {
      type: "homeworkLink",
      id: "l45-hw",
      title: "Homework",
      path: "/hw-45",
      label: "HW45 →",
      summary: "Time expressions · he/she gaps · write about a friend",
    },
  ],
};
