import type { Lesson } from "../../../types/lesson";
import {
  SOUND_U5,
  IMG44,
  foodWords,
  foodPhotoMatch,
  foodSoundPairs,
  foodListenRepeatLines,
  foodSoundTranscriptLines,
  tomFoodTicks,
  tomR12Transcript,
  radioSentences5,
  frequencyAdverbs,
  frequencyGrammarExamples,
  frequencyGrammarQuestions,
  frequencyGrammarChoices,
  frequencyStressItems,
  frequencyStressLines,
  personalFrequencyGaps,
  howOftenWordOrder,
  elaFoodTicks,
  elaR14Transcript,
  elaDialogueGaps,
  cafeWorkerPhrases,
  cafeCustomerPhrases,
  usefulPhrasesR15Transcript,
  cafeConversationOrder,
  cafeR16Transcript,
} from "./activities";
import { lesson44Homework } from "./homework";
import { foodFlashcards } from "./vocabulary";

export const lesson44: Lesson = {
  id: "44",
  number: 44,
  title: "Food and drink · Order in a café",
  level: "A1",
  moduleId: "a1-present",
  order: 44,
  status: "published",
  estimatedMinutes: 75,
  hasHomework: true,
  topic: "food · drink · frequency · order food and a drink",
  description:
    "Food and drink vocabulary, frequency adverbs, then order food and a drink in a café.",
  chips: ["never → always", "How often…?", "I’d like…, please"],
  route: "/lessons/44",
  legacyRoute: "/lesson-44",
  prevLessonPath: "/lessons/43",
  nextLessonPath: "/lessons",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 43", path: "/lessons/43", ghost: true },
    { label: "HW44 →", path: "/hw-44", ghost: true },
  ],
  homework: lesson44Homework,
  flow: [
    { href: "#l44-intro", label: "Intro" },
    { href: "#l44-vocab", label: "Vocab" },
    { href: "#l44-match", label: "1 Match" },
    { href: "#l44-audio-r10", label: "1b Repeat" },
    { href: "#l44-audio-r11", label: "2 Listen" },
    { href: "#l44-sound", label: "2 Sound" },
    { href: "#l44-healthy", label: "3 List" },
    { href: "#l44-audio-r12", label: "4 Listen" },
    { href: "#l44-ticks", label: "4a Tick" },
    { href: "#l44-tom-eat", label: "4b Tom" },
    { href: "#l44-scale", label: "5 Diagram" },
    { href: "#l44-grammar", label: "6 Grammar" },
    { href: "#l44-audio-r13", label: "7a Listen" },
    { href: "#l44-stress", label: "7a Stress" },
    { href: "#l44-audio-r13b", label: "7b Repeat" },
    { href: "#l44-personal", label: "8a You" },
    { href: "#l44-personal-b", label: "8b Compare" },
    { href: "#l44-questions", label: "9a Order" },
    { href: "#l44-speak-qa", label: "9b Ask" },
    { href: "#l44-part2", label: "Part 2" },
    { href: "#l44-cafe-photo", label: "Photo" },
    { href: "#l44-menu", label: "1 Menu" },
    { href: "#l44-audio-r14", label: "2 Listen" },
    { href: "#l44-ela-ticks", label: "2 Tick" },
    { href: "#l44-ela-gaps", label: "3 Gaps" },
    { href: "#l44-phrases", label: "4a Phrases" },
    { href: "#l44-audio-r15", label: "4a Check" },
    { href: "#l44-audio-r15b", label: "4b Repeat" },
    { href: "#l44-order-conv", label: "5a Order" },
    { href: "#l44-audio-r16", label: "5a Check" },
    { href: "#l44-practice", label: "5b Practise" },
    { href: "#l44-roleplay", label: "6 Roleplay" },
    { href: "#l44-exit", label: "Exit" },
  ],
  sections: [
    {
      type: "text",
      id: "l44-intro",
      title: "Food and drink",
      description: "Goal: talk about healthy habits with frequency adverbs.",
      body: "Today we learn food and drink words, listen to Tom, and practise always / usually / often / sometimes / never. Then we order food and a drink in a café.",
    },
    {
      type: "custom",
      id: "l44-vocab",
      kicker: "Vocabulary",
      title: "Food and drink words",
      description: "Tap a card: Ukrainian → English. Hear the English word.",
      componentKey: "vocab-flip",
      props: {
        cards: foodFlashcards,
      },
    },
    {
      type: "custom",
      id: "l44-match",
      kicker: "1a",
      title: "Match the photos and the words",
      description: "Choose the word for each photo. Then listen and check (5.10).",
      componentKey: "photo-sentence-match",
      props: {
        images: foodPhotoMatch.map((p) => ({
          id: p.id,
          src: IMG44(p.file),
          alt: p.alt,
          answer: p.answer,
        })),
        options: foodWords.map((w) => ({ value: w, label: w })),
      },
    },
    {
      type: "custom",
      id: "l44-audio-r10",
      kicker: "1b · 5.10",
      title: "Listen and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(10),
        trackLabel: "5.10",
        exercise: "1b",
        title: "Food and drink words",
        transcriptLines: [...foodListenRepeatLines],
      },
    },
    {
      type: "custom",
      id: "l44-audio-r11",
      kicker: "2 · 5.11",
      title: "Listen to the words",
      description: "Do the sounds in blue sound the same or different?",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(11),
        trackLabel: "5.11",
        exercise: "2",
        title: "Same or different?",
        transcriptLines: [...foodSoundTranscriptLines],
      },
    },
    {
      type: "custom",
      id: "l44-sound",
      kicker: "2",
      title: "Same or different?",
      description:
        "Listen to the words. Do the sounds in blue sound the same or different?",
      componentKey: "same-or-different",
      props: {
        items: foodSoundPairs.map((p) => ({ ...p })),
      },
    },
    {
      type: "custom",
      id: "l44-healthy",
      kicker: "3",
      title: "Make a list of food and drink",
      description: "Make a list of food and drink which is:",
      componentKey: "write-lists",
      props: {
        lists: [
          {
            id: "good",
            label: "good for you (healthy).",
            example: "salad",
            placeholder: "salad",
            slots: 5,
          },
          {
            id: "bad",
            label: "bad for you (unhealthy).",
            example: "chocolate",
            placeholder: "chocolate",
            slots: 5,
          },
        ],
      },
    },
    {
      type: "custom",
      id: "l44-audio-r12",
      kicker: "4 · 5.12",
      title: "Listen to a radio programme",
      description:
        "a Tick the food and drink they talk about.  b Listen again. What does Tom eat and drink?",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(12),
        trackLabel: "5.12",
        exercise: "4",
        title: "RadioTalk · Are you healthy?",
        transcriptLines: [...tomR12Transcript],
      },
    },
    {
      type: "custom",
      id: "l44-ticks",
      kicker: "a",
      title: "Tick the food and drink they talk about",
      componentKey: "tick-list",
      props: {
        shuffle: true,
        items: tomFoodTicks.map((t) => ({ ...t })),
      },
    },
    {
      type: "custom",
      id: "l44-tom-eat",
      kicker: "b",
      title: "Listen again. What does Tom eat and drink?",
      description: "Write what Tom eats and drinks.",
      componentKey: "write-lists",
      props: {
        lists: [
          {
            id: "tom-eat-drink",
            label: "Tom eats and drinks:",
            example: "tea",
            placeholder: "tea",
            slots: 6,
          },
        ],
      },
      note: "Model: tea (always) · no coffee · no sugar · cakes (often) · chocolate (usually) · fish/salad (sometimes) · meat/chicken (often)",
    },
    {
      type: "custom",
      id: "l44-scale",
      kicker: "5",
      title: "Complete the diagram",
      description:
        "Read sentences a–d from the radio programme. Complete the diagram with the words in bold.",
      componentKey: "frequency-scale",
      props: {
        options: [...frequencyAdverbs],
        steps: [
          { type: "gap", id: "1", percent: "0%", answer: "never" },
          { type: "gap", id: "2", answer: "sometimes" },
          { type: "fixed", label: "often" },
          { type: "fixed", label: "usually" },
          { type: "gap", id: "3", percent: "100%", answer: "always" },
        ],
        sentences: radioSentences5.map((s) => ({
          id: s.id,
          text: s.text,
          bold: [...s.bold],
        })),
      },
    },
    {
      type: "custom",
      id: "l44-grammar",
      kicker: "6 · Grammar",
      title: "Present simple with frequency adverbs",
      description: "Read the grammar box and choose the correct alternatives.",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "Present simple with frequency adverbs",
        examples: frequencyGrammarExamples.map((e) => ({ ...e })),
        questions: frequencyGrammarQuestions.map((q) => ({ ...q })),
        choices: frequencyGrammarChoices.map((c) => ({
          ...c,
          options: [...c.options],
        })),
      },
    },
    {
      type: "custom",
      id: "l44-audio-r13",
      kicker: "7 · 5.13",
      title: "Listen and underline the stressed syllables",
      description:
        "a Listen and underline the stressed syllables in the words in blue.  b Listen again and repeat.",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(13),
        trackLabel: "5.13",
        exercise: "7",
        title: "Frequency adverb stress",
        transcriptLines: [...frequencyStressLines],
      },
    },
    {
      type: "custom",
      id: "l44-stress",
      kicker: "a",
      title: "Underline the stressed syllables",
      description: "Tap the stressed syllable(s) in the blue words.",
      componentKey: "stress-syllable",
      props: {
        items: frequencyStressItems.map((item) => ({
          ...item,
          syllables: [...item.syllables],
          stressed: [...item.stressed],
        })),
      },
    },
    {
      type: "custom",
      id: "l44-audio-r13b",
      kicker: "b · 5.13",
      title: "Listen again and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(13),
        trackLabel: "5.13",
        exercise: "7b",
        title: "Listen again and repeat",
        transcriptLines: [...frequencyStressLines],
      },
    },
    {
      type: "fillBlank",
      id: "l44-personal",
      kicker: "8a",
      title: "Complete the sentences with frequency adverbs",
      description:
        "Complete the sentences with frequency adverbs so they are true for you. Write the words.",
      chips: [...frequencyAdverbs],
      items: personalFrequencyGaps.map((g) => ({
        id: g.id,
        before: g.before,
        after: g.after,
        correctAnswers: [...frequencyAdverbs],
      })),
    },
    {
      type: "speakingPrompt",
      id: "l44-personal-b",
      kicker: "8b",
      title: "Compare your answers",
      description: "Compare your answers with your teacher.",
      prompts: ["I sometimes have cakes for breakfast!"],
    },
    {
      type: "wordOrder",
      id: "l44-questions",
      kicker: "9a",
      title: "Put the words in the correct order to make questions",
      items: howOftenWordOrder.map((q) => ({
        id: q.id,
        scramble: q.scramble,
        parts: [...q.parts],
        answer: q.answer,
      })),
    },
    {
      type: "speakingPrompt",
      id: "l44-speak-qa",
      kicker: "9b",
      title: "Ask and answer the questions",
      description: "Ask your teacher and answer the questions in Exercise 9a.",
      prompts: howOftenWordOrder.map((q) => q.answer),
      note: "A: How often do you have breakfast at work? B: I never have breakfast at work. I always have breakfast at home.",
    },

    {
      type: "text",
      id: "l44-part2",
      kicker: "Part 2",
      title: "English in action",
      description: "Goal: order food and a drink.",
      body: "",
    },
    {
      type: "custom",
      id: "l44-cafe-photo",
      title: "Friends in a café",
      componentKey: "photo-gallery",
      props: {
        wideGrid: true,
        images: [
          {
            id: "friends",
            src: IMG44("cafe-friends.jpg"),
            caption: "Friends in a café",
            alt: "Friends sitting together at a café table",
            wide: true,
            fit: "contain",
            emoji: "☕",
          },
        ],
      },
    },
    {
      type: "custom",
      id: "l44-menu",
      kicker: "1",
      title: "Look at the menu",
      description: "What food and drinks has the café got?",
      componentKey: "photo-gallery",
      props: {
        wideGrid: true,
        images: [
          {
            id: "menu",
            src: IMG44("menu.png"),
            caption: "Café menu",
            alt: "Illustrated café menu with food and drinks",
            wide: true,
            fit: "contain",
            emoji: "📋",
          },
        ],
      },
    },
    {
      type: "custom",
      id: "l44-audio-r14",
      kicker: "2 · 5.14",
      title: "Listen and tick Ela’s food and drink",
      description: "Listen and tick Ela’s food and drink on the menu in Exercise 1.",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(14),
        trackLabel: "5.14",
        exercise: "2",
        title: "Ela in the café",
        transcriptLines: [...elaR14Transcript],
      },
    },
    {
      type: "custom",
      id: "l44-ela-ticks",
      kicker: "2",
      title: "Tick Ela’s food and drink on the menu",
      componentKey: "tick-list",
      props: {
        shuffle: true,
        items: elaFoodTicks.map((t) => ({ ...t })),
        tipCorrect: "Ela orders this",
        tipWrong: "Not Ela’s order",
      },
    },
    {
      type: "fillBlank",
      id: "l44-ela-gaps",
      kicker: "3",
      title: "Listen again and complete the conversation",
      description: "Write the missing words.",
      items: elaDialogueGaps.map((g) => ({
        id: g.id,
        before: g.before,
        after: g.after,
        correctAnswers: [...g.correctAnswers],
      })),
    },
    {
      type: "custom",
      id: "l44-phrases",
      kicker: "4a",
      title: "Useful phrases",
      description:
        "Match 1–5 with a–e in the Useful phrases box. Then listen and check your answers.",
      componentKey: "phrase-match",
      props: {
        leftHeading: "Café worker",
        rightHeading: "Customer",
        items: cafeWorkerPhrases.map((p) => ({ ...p })),
        options: cafeCustomerPhrases.map((p) => ({ ...p })),
      },
    },
    {
      type: "custom",
      id: "l44-audio-r15",
      kicker: "4a · 5.15",
      title: "Listen and check",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(15),
        trackLabel: "5.15",
        exercise: "4a",
        title: "Useful phrases",
        transcriptLines: [...usefulPhrasesR15Transcript],
      },
    },
    {
      type: "custom",
      id: "l44-audio-r15b",
      kicker: "4b · 5.15",
      title: "Listen again and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(15),
        trackLabel: "5.15",
        exercise: "4b",
        title: "Listen again and repeat",
        transcriptLines: [...usefulPhrasesR15Transcript],
      },
    },
    {
      type: "custom",
      id: "l44-order-conv",
      kicker: "5a",
      title: "Put the conversation in the correct order",
      description:
        "Tap the lines in the correct order. Then listen and check your answers.",
      componentKey: "line-order",
      props: {
        startId: "g",
        items: cafeConversationOrder.map((line) => ({ ...line })),
      },
    },
    {
      type: "custom",
      id: "l44-audio-r16",
      kicker: "5a · 5.16",
      title: "Listen and check",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(16),
        trackLabel: "5.16",
        exercise: "5a",
        title: "Café conversation",
        transcriptLines: [...cafeR16Transcript],
      },
    },
    {
      type: "speakingPrompt",
      id: "l44-practice",
      kicker: "5b",
      title: "Practise the conversation",
      description:
        "Practise the conversation with your teacher. Take turns: you are the customer, then the café worker.",
      prompts: [...cafeR16Transcript],
    },
    {
      type: "speakingPrompt",
      id: "l44-roleplay",
      kicker: "6",
      title: "Roleplay a conversation in a café",
      description:
        "Roleplay a conversation in a café with your teacher. Order food and a drink. Use the menu in Exercise 1.",
      prompts: [
        "I’d like a cheese sandwich, please.",
        "White bread, please. / Brown bread, please.",
        "Yes, please. I’d like a cup of coffee. / a bottle of water. / a cup of tea.",
        "No, thank you.",
        "How much is that?",
      ],
      note: "A (café worker): What would you like? B (you): I’d like …, please.",
    },
    {
      type: "text",
      id: "l44-exit",
      kicker: "Exit check",
      title: "Can you…?",
      body: "",
      bullets: [
        "Name food and drink: tea, coffee, salad, meat…",
        "Use frequency adverbs: I usually drink tea. I'm sometimes hungry.",
        "Ask: How often do you…?",
        "Order in a café: I’d like a sandwich, please. How much is that?",
      ],
    },
    {
      type: "homeworkLink",
      id: "l44-hw",
      kicker: "Homework",
      title: "HW44",
      path: "/hw-44",
      label: "HW44 →",
      summary: "Food flashcards, frequency practice, How often…?",
    },
  ],
};
