import type { Lesson } from "../../../types/lesson";
import {
  SOUND_U5,
  IMG44,
  foodWords,
  foodPhotoMatch,
  foodSoundPairs,
  foodListenRepeatLines,
  foodSoundTranscriptLines,
  tomFoodTicks,
  tomModelLines,
  frequencyAdverbs,
  frequencyStressLines,
  personalFrequencyStems,
  howOftenWordOrder,
} from "./activities";
import { lesson44Homework } from "./homework";
import { foodFlashcards } from "./vocabulary";

export const lesson44: Lesson = {
  id: "44",
  number: 44,
  title: "Food and drink",
  level: "A1",
  moduleId: "a1-present",
  order: 44,
  status: "published",
  estimatedMinutes: 55,
  hasHomework: true,
  topic: "food · drink · frequency adverbs · How often…?",
  description:
    "Unit 5C: food and drink vocabulary, Present Simple with frequency adverbs, and a short healthy-habits speaking survey with your teacher.",
  chips: [
    "never → always",
    "How often do you…?",
    "tea · coffee · salad",
  ],
  route: "/lessons/44",
  legacyRoute: "/lesson-44",
  prevLessonPath: "/lessons/43",
  nextLessonPath: "/lessons",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 43", path: "/lessons/43", ghost: true },
    { label: "HW44 →", path: "/hw-44", ghost: true },
  ],
  homework: lesson44Homework,
  flow: [
    { href: "#l44-intro", label: "Intro" },
    { href: "#l44-vocab", label: "Vocab" },
    { href: "#l44-match", label: "1 Match" },
    { href: "#l44-audio-r10", label: "1b Repeat" },
    { href: "#l44-audio-r11", label: "2 Listen" },
    { href: "#l44-sound", label: "2 Sound" },
    { href: "#l44-healthy", label: "3 List" },
    { href: "#l44-audio-r12", label: "4 Tom" },
    { href: "#l44-ticks", label: "4 Tick" },
    { href: "#l44-scale", label: "5 Scale" },
    { href: "#l44-grammar", label: "6 Grammar" },
    { href: "#l44-stress", label: "7 Models" },
    { href: "#l44-personal", label: "8 About you" },
    { href: "#l44-questions", label: "9 How often" },
    { href: "#l44-speak", label: "Speaking" },
    { href: "#l44-exit", label: "Exit" },
  ],
  sections: [
    {
      type: "text",
      id: "l44-intro",
      title: "Food and drink",
      description: "Goal: talk about healthy habits with frequency adverbs.",
      body: "Today we learn food and drink words, listen to Tom, and practise always / usually / often / sometimes / never.",
    },
    {
      type: "custom",
      id: "l44-vocab",
      kicker: "Vocabulary",
      title: "Food and drink words",
      description: "Tap a card: Ukrainian → English. Hear the English word.",
      componentKey: "vocab-flip",
      props: {
        cards: foodFlashcards,
      },
    },
    {
      type: "custom",
      id: "l44-match",
      kicker: "1a",
      title: "Match the photos and the words",
      description: "Choose the word for each photo. Then listen and check (5.10).",
      componentKey: "photo-sentence-match",
      props: {
        images: foodPhotoMatch.map((p) => ({
          id: p.id,
          src: IMG44(p.file),
          alt: p.alt,
          answer: p.answer,
        })),
        options: foodWords.map((w) => ({ value: w, label: w })),
      },
    },
    {
      type: "custom",
      id: "l44-audio-r10",
      kicker: "1b · 5.10",
      title: "Listen and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(10),
        trackLabel: "5.10",
        exercise: "1b",
        title: "Food and drink words",
        transcriptLines: [...foodListenRepeatLines],
      },
    },
    {
      type: "custom",
      id: "l44-audio-r11",
      kicker: "2 · 5.11",
      title: "Listen to the words",
      description:
        "Do the sounds in blue sound the same or different?",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(11),
        trackLabel: "5.11",
        exercise: "2",
        title: "Same or different?",
        transcriptLines: [...foodSoundTranscriptLines],
      },
    },
    {
      type: "custom",
      id: "l44-sound",
      kicker: "2",
      title: "Same or different?",
      description:
        "Listen to the words. Do the sounds in blue sound the same or different?",
      componentKey: "same-or-different",
      props: {
        items: foodSoundPairs.map((p) => ({ ...p })),
      },
    },
    {
      type: "custom",
      id: "l44-healthy",
      kicker: "3",
      title: "Make a list of food and drink",
      description: "Make a list of food and drink which is:",
      componentKey: "write-lists",
      props: {
        lists: [
          {
            id: "good",
            label: "good for you (healthy).",
            example: "salad",
            placeholder: "salad, …",
          },
          {
            id: "bad",
            label: "bad for you (unhealthy).",
            example: "chocolate",
            placeholder: "chocolate, …",
          },
        ],
      },
    },
    {
      type: "custom",
      id: "l44-audio-r12",
      kicker: "4a · 5.12",
      title: "Listen to Tom",
      description: "Tick the food and drink words Tom talks about.",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(12),
        trackLabel: "5.12",
        exercise: "4a",
        title: "Tom · food and drink",
        transcriptLines: [...tomModelLines],
      },
    },
    {
      type: "custom",
      id: "l44-ticks",
      kicker: "4a",
      title: "What does Tom talk about?",
      description: "Tick the words Tom talks about.",
      componentKey: "tick-list",
      props: {
        items: tomFoodTicks.map((t) => ({ ...t })),
      },
    },
    {
      type: "text",
      id: "l44-models",
      kicker: "4b",
      title: "Frequency in Tom’s sentences",
      body: "Read the sentences. Notice never / always / often / usually / sometimes.",
      bullets: [...tomModelLines],
    },
    {
      type: "custom",
      id: "l44-scale",
      kicker: "5",
      title: "Complete the frequency scale",
      description: "Fill the gaps: 1 (0%), 2, and 3 (100%).",
      componentKey: "frequency-scale",
      props: {
        options: [...frequencyAdverbs],
        steps: [
          { type: "gap", id: "1", percent: "0%", answer: "never" },
          { type: "gap", id: "2", answer: "sometimes" },
          { type: "fixed", label: "often" },
          { type: "fixed", label: "usually" },
          { type: "gap", id: "3", percent: "100%", answer: "always" },
        ],
      },
    },
    {
      type: "text",
      id: "l44-grammar",
      kicker: "6 · Grammar",
      title: "Present Simple + frequency adverbs",
      description: "Use frequency adverbs to say how often you do things.",
      body: "Adverbs: always, usually, often, sometimes, never.",
      bullets: [
        "Before most verbs: I often eat sandwiches. / I never drink tea.",
        "After be: I'm sometimes late home for dinner.",
        "Ask with How often…? How often do you eat meat? / How often are you late for work?",
      ],
    },
    {
      type: "custom",
      id: "l44-audio-r13",
      kicker: "7a · 5.13",
      title: "Listen to the stress",
      description: "Listen and notice the stressed part of the adverb.",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(13),
        trackLabel: "5.13",
        exercise: "7a",
        title: "Frequency adverb stress",
        transcriptLines: [...frequencyStressLines],
      },
    },
    {
      type: "text",
      id: "l44-stress",
      kicker: "7",
      title: "Model sentences",
      body: "Read and notice the frequency adverb.",
      bullets: [...frequencyStressLines],
    },
    {
      type: "speakingPrompt",
      id: "l44-personal",
      kicker: "8",
      title: "True for you",
      description:
        "Complete with a frequency adverb. Then compare with your teacher.",
      prompts: [...personalFrequencyStems],
    },
    {
      type: "wordOrder",
      id: "l44-questions",
      kicker: "9a",
      title: "How often…? Put the words in order",
      items: howOftenWordOrder.map((q) => ({
        id: q.id,
        scramble: q.scramble,
        parts: [...q.parts],
        answer: q.answer,
      })),
    },
    {
      type: "speakingPrompt",
      id: "l44-speak-qa",
      kicker: "9b",
      title: "Ask and answer",
      description: "Ask your teacher and answer the questions.",
      prompts: howOftenWordOrder.map((q) => q.answer),
    },
    {
      type: "speakingPrompt",
      id: "l44-speak",
      kicker: "Speaking",
      title: "Are they healthy?",
      description:
        "Ask these How often…? questions with your teacher. Are the habits healthy or not very healthy?",
      prompts: [
        "How often do you eat salad / fruit / fish?",
        "How often do you eat cakes / chocolate / sweet food?",
        "How often do you drink water / tea / coffee?",
        "How often do you play sport or walk?",
      ],
    },
    {
      type: "text",
      id: "l44-exit",
      kicker: "Exit check",
      title: "Can you…?",
      body: "",
      bullets: [
        "Name food and drink: tea, coffee, salad, meat…",
        "Use frequency adverbs: I usually drink tea. I'm sometimes hungry.",
        "Ask: How often do you…?",
      ],
    },
    {
      type: "homeworkLink",
      id: "l44-hw",
      kicker: "Homework",
      title: "HW44",
      path: "/hw-44",
      label: "HW44 →",
      summary: "Food flashcards, frequency practice, How often…?",
    },
  ],
};
