import type { Lesson } from "../../../types/lesson";
import {
  SOUND_U6,
  IMG47,
  skillPhotoMatch,
  skillMatchPhrases,
  skillsR13Transcript,
  skillsHeardTicks,
  gloriaSkillTicks,
  gloriaR15Transcript,
  canGrammarGaps,
  canSoundPairs,
  canR16Transcript,
  saraRodrigoChoices,
  jobCanModels,
  clubNotebookGroups,
  skillSpeakPrompts,
  VIDEO_ID,
  videoDiscussPrompts,
} from "./activities";
import { lesson47Homework } from "./homework";
import {
  clothesFlashcards,
  clothesPictureFlashcards,
  skillFlashcards,
} from "./vocabulary";

export const lesson47: Lesson = {
  id: "47",
  number: 47,
  title: "Skills",
  level: "A1",
  moduleId: "a1-present",
  order: 47,
  status: "published",
  estimatedMinutes: 70,
  hasHomework: true,
  topic: "skills · can / can’t for ability",
  description:
    "Match skills to photos, listen about Gloria’s abilities, practise can / can’t, then write club questions in a notebook and speak with your teacher.",
  chips: ["Can you…?", "Yes, I can.", "No, I can’t."],
  route: "/lessons/47",
  legacyRoute: "/lesson-47",
  prevLessonPath: "/lessons/46",
  nextLessonPath: "/lessons/48",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 46", path: "/lessons/46", ghost: true },
    { label: "HW47 →", path: "/hw-47", ghost: true },
  ],
  homework: lesson47Homework,
  flow: [
    { href: "#l47-intro", label: "Intro" },
    { href: "#l47-vocab", label: "Vocab" },
    { href: "#l47-match", label: "1 Match" },
    { href: "#l47-audio-r13", label: "1b Listen" },
    { href: "#l47-audio-r14", label: "1c Hear" },
    { href: "#l47-heard", label: "1c Tick" },
    { href: "#l47-website", label: "2 Website" },
    { href: "#l47-audio-r15", label: "2b Listen" },
    { href: "#l47-gloria", label: "2c Tick" },
    { href: "#l47-grammar", label: "3 Grammar" },
    { href: "#l47-audio-r16", label: "4 Sound" },
    { href: "#l47-same-diff", label: "4 Same?" },
    { href: "#l47-interview", label: "5 Interview" },
    { href: "#l47-jobs", label: "6 Jobs" },
    { href: "#l47-notebook", label: "7 Notebook" },
    { href: "#l47-youglish", label: "Pronounce" },
    { href: "#l47-speak", label: "8 Speak" },
    { href: "#l47-exit", label: "Exit" },
    { href: "#l47-video", label: "Video" },
    { href: "#l47-video-talk", label: "Discuss" },
    { href: "#l47-clothes", label: "Clothes" },
    { href: "#l47-clothes-pics", label: "Clothes pics" },
  ],
  sections: [
    {
      type: "text",
      id: "l47-intro",
      title: "Skills",
      description: "Unit 6C",
      body: "Goal: ask and answer about things you can and can’t do.",
      bullets: [
        "Grammar: can / can’t for ability",
        "Vocabulary: skills",
      ],
    },
    {
      type: "custom",
      id: "l47-vocab",
      kicker: "Vocabulary",
      title: "Skill phrases",
      description: "Tap: Ukrainian → English.",
      componentKey: "vocab-flip",
      props: {
        cards: skillFlashcards,
      },
    },
    {
      type: "custom",
      id: "l47-match",
      kicker: "1a",
      title: "Match photos A–L with skills 1–12",
      description: "Choose the skill for each picture.",
      componentKey: "photo-sentence-match",
      props: {
        options: skillMatchPhrases.map((s) => ({ ...s })),
        images: skillPhotoMatch.map((p) => ({
          id: p.id,
          src: IMG47(p.file),
          alt: p.alt,
          answer: p.answer,
        })),
      },
    },
    {
      type: "custom",
      id: "l47-audio-r13",
      kicker: "1b · 6.13",
      title: "Listen and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(13),
        trackLabel: "6.13",
        title: "Skills",
        exercise: "1b",
        transcriptLines: [...skillsR13Transcript],
      },
    },
    {
      type: "custom",
      id: "l47-audio-r14",
      kicker: "1c · 6.14",
      title: "Listen · which activities?",
      description: "Listen. Which activities do you hear?",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(14),
        trackLabel: "6.14",
        title: "Skill sounds",
        exercise: "1c",
        transcriptLines: [
          "1. play football",
          "2. ride a horse",
          "3. swim",
          "4. sing",
          "5. fly a plane",
          "6. make clothes",
        ],
      },
    },
    {
      type: "custom",
      id: "l47-heard",
      kicker: "1c",
      title: "Tick the activities you hear",
      componentKey: "tick-list",
      props: {
        shuffle: true,
        items: skillsHeardTicks.map((t) => ({ ...t })),
      },
    },
    {
      type: "custom",
      id: "l47-website",
      kicker: "2a",
      title: "Look at the website. What does it do?",
      description: "Discuss with your teacher.",
      componentKey: "job-site-mock",
      props: {
        siteName: "ChooseYourJob.com",
        steps: [
          "Add your personal details (e.g. name, email address, etc.).",
          "Answer the questions.",
          "See which jobs we think are right for you!",
        ],
        tipLabel: "Підказка",
        tipNote:
          "Два трохи різні способи сказати майже одну й ту саму ідею.",
        tipPairs: [
          {
            en: "It helps you find the right job for you.",
            ua: "Сайт допомагає знайти саме підходящу для тебе професію.",
          },
          {
            en: "It helps people choose a job.",
            ua: "Сайт допомагає людям обрати якусь професію.",
          },
        ],
      },
    },
    {
      type: "custom",
      id: "l47-audio-r15",
      kicker: "2b · 6.15",
      title: "Listen · Yusuf and Gloria",
      description:
        "Listen to the conversation. Tick the things Gloria can do.",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(15),
        trackLabel: "6.15",
        title: "ChooseYourJob.com · Gloria",
        exercise: "2b",
        transcriptLines: [...gloriaR15Transcript],
      },
    },
    {
      type: "custom",
      id: "l47-gloria",
      kicker: "2c",
      title: "What can Gloria do?",
      description: "Tick the skills Gloria can do. (use a computer is ticked in the book.)",
      componentKey: "tick-list",
      props: {
        items: gloriaSkillTicks.map((t) => ({ ...t })),
        tipCorrect: "Gloria can do this",
        tipWrong: "Gloria can’t do this",
      },
    },
    {
      type: "fillBlank",
      id: "l47-grammar",
      kicker: "3",
      title: "can / can’t for ability",
      description:
        "Read the grammar box and choose the correct alternatives. After can / can’t we use the base verb (sing, not sings). + Yes, I can. − No, I can’t.",
      chips: ["can", "can't", "base verb"],
      items: canGrammarGaps.map((g) => ({
        id: g.id,
        before: g.before ? `${g.before} ` : "",
        after: g.after,
        correctAnswers: [...g.answers],
        options: [...g.options],
        choiceMode: "buttons" as const,
      })),
    },
    {
      type: "custom",
      id: "l47-audio-r16",
      kicker: "4a · 6.16",
      title: "Pronunciation · can / can’t",
      description:
        "Listen. Do the words in blue sound the same or different?",
      componentKey: "native-audio",
      props: {
        src: SOUND_U6(16),
        trackLabel: "6.16",
        title: "can · strong and weak",
        exercise: "4a",
        transcriptLines: [...canR16Transcript],
      },
    },
    {
      type: "custom",
      id: "l47-same-diff",
      kicker: "4a",
      title: "Same or different?",
      description: "Listen again if you need to. Then repeat with your teacher (4b).",
      componentKey: "same-or-different",
      props: {
        items: canSoundPairs.map((p) => ({ ...p })),
        tip: "can’t often sounds like /kɑːnt/. Weak can in questions can sound shorter.",
      },
    },
    {
      type: "custom",
      id: "l47-interview",
      kicker: "5",
      title: "Interview · computer club teacher",
      description:
        "Read the interview for a computer club teacher and choose the correct alternatives.",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "can / can’t · questions and short answers",
        examples: [
          { id: "e1", text: "*Can* you use a computer?" },
          { id: "e2", text: "Yes, I *can*. / No, I *can’t*." },
        ],
        choices: saraRodrigoChoices.map((c) => ({ ...c })),
      },
    },
    {
      type: "speakingPrompt",
      id: "l47-jobs",
      kicker: "6a · Prepare",
      title: "Write three questions with can for each job",
      description:
        "Look at the jobs. Say or write three Can you…? questions for each. Then ask your teacher (6b).",
      prompts: jobCanModels.map((j) => `${j.job}: … / … / …`),
      models: jobCanModels.map((j) => j.models.join(" · ")),
      hideModels: true,
      note: "Example: taxi driver → Can you drive?",
    },
    {
      type: "custom",
      id: "l47-notebook",
      kicker: "7 · Prepare",
      title: "Questions for club teachers",
      description:
        "Read the information. Write questions for the club teachers in the notebook. Type on each line.",
      componentKey: "club-notebook",
      props: {
        heading: "Questions for club teachers",
        intro: "Ask these questions to choose good teachers:",
        groups: clubNotebookGroups.map((g) => ({
          id: g.id,
          title: g.title,
          lines: g.lines.map((l) => ({ ...l })),
        })),
      },
    },
    {
      type: "text",
      id: "l47-youglish",
      kicker: "Pronunciation",
      title: "can / can’t · YouGlish",
      body: "Open each link. Listen and repeat. Practise with your teacher if you need help.",
      links: [
        {
          href: "https://youglish.com/pronounce/can/english",
          label: "can · YouGlish ↗",
        },
        {
          href: "https://youglish.com/pronounce/can%27t/english",
          label: "can’t · YouGlish ↗",
        },
      ],
    },
    {
      type: "speakingPrompt",
      id: "l47-speak",
      kicker: "8 · Speak",
      title: "Ask and answer with your teacher",
      description:
        "Use your notebook questions. Ask your teacher. Who is a good teacher for each club?",
      prompts: [...skillSpeakPrompts],
      note: "Model: Can you run? — Yes, I can. / No, I can’t.",
    },
    {
      type: "text",
      id: "l47-exit",
      kicker: "Exit",
      title: "Today you can…",
      body: "name skills; ask Can you…?; answer Yes, I can. / No, I can’t.; say what you can and can’t do.",
      bullets: [
        "Can you swim? — Yes, I can.",
        "I can cook fish. I can’t drive.",
        "What can you cook? — I can cook chicken.",
      ],
    },
    {
      type: "custom",
      id: "l47-video",
      kicker: "Extra · Video",
      title: "Listening quiz · subject pronouns",
      description:
        "Watch the video with your teacher. Listen for I / you / he / she / we / they.",
      componentKey: "youtube-video",
      props: {
        videoId: VIDEO_ID,
        iframeTitle: "Beginner English Listening Quiz · Subject Pronouns",
      },
    },
    {
      type: "speakingPrompt",
      id: "l47-video-talk",
      kicker: "Extra · Discuss",
      title: "Talk about the video",
      description: "Discuss the questions with your teacher.",
      prompts: [...videoDiscussPrompts],
      note: "Use can / can’t too: What can he do? What can you do?",
    },
    {
      type: "custom",
      id: "l47-clothes",
      kicker: "Extra · Vocabulary",
      title: "Clothes",
      description: "Tap: Ukrainian → English. Then say what you wear today.",
      componentKey: "vocab-flip",
      props: {
        cards: clothesFlashcards,
      },
    },
    {
      type: "custom",
      id: "l47-clothes-pics",
      kicker: "Extra · Vocabulary",
      title: "Clothes · pictures",
      description: "Tap a picture to flip. Say the English word.",
      componentKey: "image-vocab-flip",
      props: {
        cards: clothesPictureFlashcards,
      },
    },
    {
      type: "homeworkLink",
      id: "l47-hw",
      title: "Homework",
      path: "/hw-47",
      label: "HW47 →",
      summary: "Skills match · can/can’t · write about abilities",
    },
  ],
};
