import type { Lesson } from "../../../types/lesson";
import {
  SOUND_U4,
  VIDEO_ID,
  contractionListen,
  descMatch,
  grammarPlusMinus,
  hasHaveChoose,
  homeworkFixGroups,
  homeworkFixLines,
  labelBank,
  lucaText,
  matchPhotos,
  photoLabels,
  profilePhotos,
  sofiaSentences,
  speakPrepare,
  whoIsWho,
  wordMapExtra,
  wordMapFixed,
} from "./activities";
import { lesson38Homework } from "./homework";

export const lesson38: Lesson = {
  id: "38",
  number: 38,
  title: "You've got a friend",
  level: "A1",
  moduleId: "a1-present",
  order: 38,
  status: "published",
  estimatedMinutes: 55,
  hasHomework: true,
  topic: "Unit 4A · have / has got · describe people",
  description:
    "Unit 4A: describe people with have/has got, match photos, and talk about a friend.",
  chips: ["have got / has got", "hair · eyes · age", "I've got / He's got"],
  legacyRoute: "/lesson-38",
  route: "/lessons/38",
  prevLessonPath: "/lessons/37",
  nextLessonPath: "/lesson-39",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 37", path: "/lessons/37", ghost: true },
    { label: "HW38 →", path: "/hw-38", ghost: true },
    { label: "Lesson 39 →", path: "/lesson-39", ghost: true },
  ],
  homework: lesson38Homework,
  flow: [
    { href: "#l38-hwfix", label: "Fix HW" },
    { href: "#l38-read", label: "1 Friends" },
    { href: "#l38-who", label: "Who?" },
    { href: "#l38-labels", label: "2 Labels" },
    { href: "#l38-match-photos", label: "3 Photos" },
    { href: "#l38-match", label: "Match" },
    { href: "#l38-audio-r1", label: "Audio" },
    { href: "#l38-map", label: "4 Word map" },
    { href: "#l38-grammar", label: "5 Grammar" },
    { href: "#l38-listen", label: "6 Listen" },
    { href: "#l38-choose", label: "7 Choose" },
    { href: "#l38-sofia-photo", label: "8 Sofia" },
    { href: "#l38-sofia", label: "Sentences" },
    { href: "#l38-speak1", label: "9 Speak" },
    { href: "#l38-video", label: "4B Video" },
    { href: "#l38-exit", label: "Exit" },
  ],
  sections: [
    {
      type: "custom",
      id: "l38-hwfix",
      kicker: "Warm-up · Homework",
      title: "Fix the mistakes",
      description:
        "Усі речення з ДЗ, які треба поправити. Відредагуй рядок → Check. Hint показує підказку. Потім прочитай правильні речення вголос із учителем. 34, 38 і 42 уже правильні — їх немає тут.",
      componentKey: "homework-fix",
      props: {
        groups: homeworkFixGroups,
        lines: homeworkFixLines,
      },
    },
    {
      type: "text",
      id: "l38-read",
      kicker: "1 · 4A Reading",
      title: "You've got a friend",
      description:
        "Read the profile and look at the photos. Which person is Luca? Which person is Mehmet?",
      body: "",
      bullets: [...lucaText],
    },
    {
      type: "custom",
      id: "l38-read-photos",
      kicker: "Photos",
      title: "Photo A · Photo B",
      componentKey: "photo-gallery",
      props: {
        wideGrid: true,
        images: profilePhotos.map((p) => ({
          id: p.id,
          file: p.file,
          emoji: p.emoji,
          caption: p.caption,
          note: p.note,
          alt: `${p.caption} — ${p.note ?? "profile"}`,
        })),
      },
    },
    {
      type: "multipleChoiceGroup",
      id: "l38-who",
      kicker: "1b · Who is who?",
      title: "Which photo?",
      items: whoIsWho.map((item) => ({
        id: item.id,
        prompt: item.prompt,
        options: ["A", "B"],
        correctAnswer: item.answer,
      })),
    },
    {
      type: "multipleChoiceGroup",
      id: "l38-labels",
      kicker: "2 · Vocabulary",
      title: "Match the labels",
      description:
        "Look at the numbers on the photos. Match 1–7 with the words in the box.",
      chips: [...labelBank],
      items: photoLabels.map((item) => ({
        id: `label-${item.n}`,
        prompt: `${item.n}. Photo ${item.photo} · ${item.hint}`,
        options: [...labelBank],
        correctAnswer: item.answer,
      })),
    },
    {
      type: "custom",
      id: "l38-match-photos",
      kicker: "3a · Photos A–D",
      title: "Look at the photos",
      description:
        "Match descriptions 1–4 with photos A–D. Then listen and repeat the words in bold.",
      componentKey: "photo-gallery",
      props: {
        images: matchPhotos.map((p) => ({
          id: p.id,
          file: p.file,
          emoji: p.emoji,
          caption: p.caption,
          alt: p.caption,
        })),
      },
    },
    {
      type: "multipleChoiceGroup",
      id: "l38-match",
      kicker: "3a · Match",
      title: "Match descriptions 1–4",
      items: descMatch.map((item) => ({
        id: item.id,
        prompt: `${item.id}. ${item.text}`,
        options: ["A", "B", "C", "D"],
        correctAnswer: item.answer,
      })),
    },
    {
      type: "custom",
      id: "l38-audio-r1",
      kicker: "3b · Audio",
      title: "Listen and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U4(1),
        trackLabel: "R1",
        exercise: "3b · 4.1",
        title:
          "Listen and repeat the words in bold: blonde hair, blue eyes, in her 50s…",
        ariaLabel: "Unit 4 track R1 — describing people vocabulary",
      },
    },
    {
      type: "custom",
      id: "l38-map",
      kicker: "3c · Word map",
      title: "Add more words",
      description:
        "Watch the map appear. Then tap a new word and tap colours or the body. Discuss extra words with your teacher.",
      componentKey: "lesson38-word-map",
      props: {
        fixed: wordMapFixed,
        extras: wordMapExtra,
      },
    },
    {
      type: "custom",
      id: "l38-grammar",
      kicker: "Grammar",
      title: "have / has got",
      description: "5 Read and complete the grammar box.",
      componentKey: "lesson38-grammar-have-got",
      props: {
        items: grammarPlusMinus,
      },
    },
    {
      type: "text",
      id: "l38-listen",
      kicker: "6a · Contractions",
      title: "Listen to the sentences",
      description:
        "Notice the pronunciation of the words in blue. Then listen again and repeat (6b).",
      body: "",
      bullets: contractionListen.map(
        (item) => `${item.contraction} ${item.rest}`,
      ),
    },
    {
      type: "custom",
      id: "l38-audio-r2",
      kicker: "6a · Audio",
      title: "I've / You've / We've / They've / He's / She's",
      componentKey: "native-audio",
      props: {
        src: SOUND_U4(2),
        trackLabel: "R2",
        exercise: "4A · 4.2",
        title: "I've / You've / We've / They've / He's / She's",
        ariaLabel: "Unit 4 track R2 — have got contractions",
        transcriptLines: contractionListen.map(
          (item) => `${item.contraction} ${item.rest}`,
        ),
      },
    },
    {
      type: "fillBlank",
      id: "l38-choose",
      kicker: "7 · Choose",
      title: "Choose the correct alternatives",
      items: hasHaveChoose.map((item) => ({
        id: item.id,
        before: item.before,
        after: item.after,
        options: [...item.options],
        correctAnswers: [item.answer],
        choiceMode: "buttons" as const,
      })),
    },
    {
      type: "custom",
      id: "l38-sofia-photo",
      kicker: "8 · Sentences",
      title: "Sofia and Jules",
      description:
        "8 Look at the picture and make sentences using the prompts.",
      componentKey: "photo-gallery",
      props: {
        images: [
          {
            id: "sofia",
            file: "sofia-jules.png",
            emoji: "👨‍👩‍👦",
            caption: "Sofia and Jules · Paris",
            note: "office worker · son · 30s",
            alt: "Sofia and Jules in Paris",
            wide: true,
          },
        ],
      },
    },
    {
      type: "wordOrder",
      id: "l38-sofia",
      kicker: "8 · Word order",
      title: "Make sentences",
      items: sofiaSentences.map((item) => ({
        scramble: item.scramble,
        parts: [...item.parts],
        answer: item.answer,
      })),
    },
    {
      type: "custom",
      id: "l38-speak1",
      kicker: "Speaking",
      title: "Talk about a friend",
      componentKey: "lesson38-friend-speak",
      props: {
        prepare: speakPrepare,
        photo: {
          file: "friends-street.png",
          emoji: "👫",
          caption: "A friend",
          alt: "Friends on the street",
          wide: true,
        },
        prompts: [
          {
            id: "10a",
            label: "10a",
            text: "Describe yourself. Then describe your friend from Exercise 9. Talk with your teacher.",
            model:
              "OK, my name is Piotr. My friend's name is Basia. We're from Poland. I'm a teacher. I've got …",
          },
          {
            id: "10b",
            label: "10b",
            text: "Tell your teacher: are you very different from your friend?",
            model:
              "Piotr is very different from his friend Basia. Piotr is a teacher, but Basia is …",
          },
        ],
      },
    },
    {
      type: "custom",
      id: "l38-video",
      kicker: "Video · 4B",
      title: "Listening quiz · adjectives",
      description:
        "Watch the video with your teacher. The 4B vocabulary is in Lesson 39.",
      componentKey: "youtube-video",
      props: {
        videoId: VIDEO_ID,
        iframeTitle: "Beginner English Listening Quiz — Adjectives",
      },
      note: "Continue in Lesson 39 · Have you got it?",
    },
    {
      type: "text",
      id: "l38-exit",
      kicker: "Exit check",
      title: "Can you…?",
      body: "",
      bullets: [
        "Describe a person: He's got brown hair. She's in her 30s.",
        "Say + and −: I've got / I haven't got / She hasn't got.",
      ],
    },
    {
      type: "homeworkLink",
      id: "l38-hw",
      kicker: "Homework",
      title: "HW38",
      path: "/hw-38",
      label: "HW38 →",
      summary: "Practice have/has got, possessives, and write about a friend.",
    },
  ],
};
