import type { Lesson } from "../../../types/lesson";
import {
  bridgeGaps,
  todayYesterdayDrill,
  timelineAskPrompts,
  timelineChoiceHelp,
  controlledStoryGaps,
  markText,
  markQuiz,
  yesterdaySpeakPrompts,
  yesterdaySpeakModels,
  delayedFixChoices,
  scenarioWorkDayPrompts,
  scenarioWorkDayModels,
  scenarioHomePastPrompts,
  scenarioHomePastModels,
  scenarioFoodSkillsPrompts,
  scenarioFoodSkillsModels,
  scenarioWeekendPastPrompts,
  scenarioWeekendPastModels,
} from "./activities";
import { lesson49Homework } from "./homework";
import { lesson49TeacherScript } from "./teacherScript";
import { yesterdayFlashcards } from "./vocabulary";

export const lesson49: Lesson = {
  id: "49",
  number: 49,
  title: "Review · Yesterday",
  level: "A1",
  moduleId: "a1-present",
  order: 49,
  status: "published",
  estimatedMinutes: 60,
  hasHomework: true,
  topic: "Yesterday story · Past Simple · was/were · core verbs",
  description:
    "Speaking project: tell your yesterday — morning → evening — with was, got up, had, went, worked, played/watched.",
  chips: ["was", "got up", "went", "worked", "Did you…?"],
  route: "/lessons/49",
  legacyRoute: "/lesson-49",
  prevLessonPath: "/lessons/48",
  nextLessonPath: "/lessons",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 48", path: "/lessons/48", ghost: true },
    { label: "HW49 →", path: "/hw-49", ghost: true },
  ],
  homework: lesson49Homework,
  flow: [
    { href: "#l49-teacher", label: "Сценарій", teacherOnly: true },
    { href: "#l49-intro", label: "Goal" },
    { href: "#l49-bridge", label: "Today/Yest." },
    { href: "#l49-verbs", label: "6 verbs" },
    { href: "#l49-drill", label: "Drill" },
    { href: "#l49-timeline", label: "Timeline" },
    { href: "#l49-help", label: "Choice" },
    { href: "#l49-controlled", label: "Story gaps" },
    { href: "#l49-mark", label: "Mark" },
    { href: "#l49-quiz", label: "Check" },
    { href: "#l49-story1", label: "Attempt 1" },
    { href: "#l49-fix", label: "Fix 3" },
    { href: "#l49-story2", label: "Attempt 2" },
    { href: "#l49-sc-work", label: "Work day" },
    { href: "#l49-sc-home", label: "Home past" },
    { href: "#l49-sc-food", label: "Food" },
    { href: "#l49-sc-weekend", label: "Weekend" },
    { href: "#l49-exit", label: "Exit" },
  ],
  sections: [
    {
      type: "custom",
      id: "l49-teacher",
      teacherOnly: true,
      kicker: "Тільки для вчителя",
      title: "Сценарій уроку",
      description:
        "Видно лише з учительного акаунта (VITE_TEACHER_EMAIL). Учень цей блок не бачить.",
      componentKey: "teacher-script",
      props: {
        heading: lesson49TeacherScript.heading,
        goal: lesson49TeacherScript.goal,
        blocks: lesson49TeacherScript.blocks.map((b) => ({
          time: b.time,
          title: b.title,
          lines: [...b.lines],
        })),
        tips: [...lesson49TeacherScript.tips],
        homework: [...lesson49TeacherScript.homework],
      },
    },
    {
      type: "text",
      id: "l49-intro",
      title: "Yesterday · speaking project",
      description: "One clear goal. ~70% speaking.",
      body: "Today you tell a real yesterday story. No Past Continuous. No third form. No big irregular list.",
      bullets: [
        "Tell your yesterday in a short story (morning → evening).",
        "Answer: What did you do? Where did you go? Did you work? Were you tired?",
        "Core verbs: got up · had · went · worked · played · watched (+ was).",
      ],
    },
    {
      type: "fillBlank",
      id: "l49-bridge",
      kicker: "0–5 · Warm-up",
      title: "Today → yesterday",
      description:
        "Feel the contrast. Don’t explain all of did yet — hear today vs yesterday.",
      chips: ["was", "worked", "went", "had"],
      items: bridgeGaps.map((g) => ({
        id: g.id,
        before: `${g.before} `,
        after: g.after,
        correctAnswers: [...g.answers],
        options: [...g.options],
        choiceMode: "buttons" as const,
      })),
    },
    {
      type: "custom",
      id: "l49-verbs",
      kicker: "5–15 · Key verbs",
      title: "Six past phrases",
      description:
        "Only these for speaking today. Tap UA → EN.",
      componentKey: "vocab-flip",
      props: { cards: yesterdayFlashcards },
    },
    {
      type: "custom",
      id: "l49-drill",
      kicker: "5–15 · Drill",
      title: "Today I… · Yesterday you…",
      description:
        "Teacher: “Today I go to work. Yesterday?” Student: “Yesterday you went to work.”",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "Today → Yesterday",
        examples: [
          { id: "e1", text: "Today I *go* → Yesterday you *went*." },
          { id: "e2", text: "Today I *play* → Yesterday you *played*." },
        ],
        choices: todayYesterdayDrill.map((c) => ({
          id: c.id,
          before: `${c.before} `,
          after: c.after,
          options: [...c.options],
          answer: c.answer,
        })),
      },
    },
    {
      type: "speakingPrompt",
      id: "l49-timeline",
      kicker: "15–25 · Timeline",
      title: "Morning → afternoon → evening → night",
      description:
        "Teacher asks. You answer. If you don’t remember, use a choice (next block).",
      prompts: [...timelineAskPrompts],
      note: "Timeline on screen/board. Keywords only — not full written sentences for the student.",
    },
    {
      type: "speakingPrompt",
      id: "l49-help",
      kicker: "If you freeze",
      title: "Choose A or B",
      description: "Stay in the story. Don’t stop for a long grammar talk.",
      prompts: [...timelineChoiceHelp],
    },
    {
      type: "fillBlank",
      id: "l49-controlled",
      kicker: "25–35 · Controlled story",
      title: "Fill, then say the whole story",
      description:
        "Yesterday I ___ up at ___. I ___ breakfast. Then I ___ to ___. … First insert forms aloud, then tell the full text.",
      items: controlledStoryGaps.map((g) => ({
        id: g.id,
        before: `${g.before} `,
        after: g.after,
        correctAnswers: [...g.answers],
        options: [...g.options],
        choiceMode: "buttons" as const,
      })),
    },
    {
      type: "text",
      id: "l49-mark",
      kicker: "35–43 · Reading",
      title: "Mark’s yesterday",
      description: "Short text. Then quiz. Then: Is Mark’s yesterday similar to yours?",
      body: markText.join(" "),
    },
    {
      type: "multipleChoiceGroup",
      id: "l49-quiz",
      kicker: "35–43 · Check",
      title: "Mark · questions",
      items: markQuiz.map((q) => ({
        id: q.id,
        prompt: q.prompt,
        options: [...q.options],
        correctAnswer: q.correctAnswer,
      })),
    },
    {
      type: "speakingPrompt",
      id: "l49-story1",
      kicker: "43–52 · Attempt 1",
      title: "Your yesterday",
      description:
        "Use the timeline. Don’t read full sentences. Teacher does not interrupt for 45–60 seconds. Max 3 notes for correction.",
      prompts: [...yesterdaySpeakPrompts],
      models: [...yesterdaySpeakModels],
      hideModels: true,
      note: "Підказка = model once. Then your own day.",
    },
    {
      type: "custom",
      id: "l49-fix",
      kicker: "52–56 · Delayed correction",
      title: "Only three fixes",
      description:
        "Fix the pattern, then say the full correct sentence. Only: was worked → worked · goed → went · have yesterday → had.",
      componentKey: "frequency-grammar",
      props: {
        boxTitle: "Choose the correct sentence",
        examples: [
          { id: "e1", text: "I *worked*. (not was worked)" },
          { id: "e2", text: "I *went* to work. (not goed)" },
        ],
        choices: delayedFixChoices.map((c) => ({
          id: c.id,
          before: c.before,
          after: c.after,
          options: [...c.options],
          answer: c.answer,
        })),
      },
    },
    {
      type: "speakingPrompt",
      id: "l49-story2",
      kicker: "56–60 · Attempt 2",
      title: "Your yesterday · again",
      description:
        "Second attempt without the full template. Feel the success.",
      prompts: [
        "Tell your yesterday again: morning → evening.",
        "Use: was · got up · had · went · worked · played/watched.",
      ],
      note: "Teacher: “Today you used was, got up, had, went, worked, played/watched. You can already tell a real story about yesterday.”",
    },
    {
      type: "text",
      id: "l49-sc-intro",
      kicker: "Extra · Speaking scenarios",
      title: "Practice L30–47 through yesterday",
      description:
        "Pick 1–2 scenarios (~5 min each). Past Simple is the spine; Present only as contrast (usually vs yesterday).",
      body: "Recycle: work day · home jobs · food/café · can/can’t (light) · was/were · Did you…?",
      bullets: [
        "Short answers: Yes, I did. / No, I didn’t. / Yes, I was. / No, I wasn’t.",
        "Do not open Past Continuous or a big irregular list.",
      ],
    },
    {
      type: "speakingPrompt",
      id: "l49-sc-work",
      kicker: "Scenario A · Work day (L42–43, L46)",
      title: "Yesterday at work",
      description:
        "Tell your work day yesterday. Contrast with what you usually do. Ask your teacher about her yesterday at work.",
      prompts: [...scenarioWorkDayPrompts],
      models: [...scenarioWorkDayModels],
      hideModels: true,
      note: "L42–43 recycle + work chunks.",
    },
    {
      type: "speakingPrompt",
      id: "l49-sc-home",
      kicker: "Scenario B · Home (L45–46)",
      title: "Yesterday at home",
      description:
        "Housework and free time yesterday. Use Did you…? and usually vs yesterday.",
      prompts: [...scenarioHomePastPrompts],
      models: [...scenarioHomePastModels],
      hideModels: true,
      note: "L45–46 in the past.",
    },
    {
      type: "speakingPrompt",
      id: "l49-sc-food",
      kicker: "Scenario C · Food & skills (L44, L47)",
      title: "Breakfast · café · can you…?",
      description:
        "Food yesterday + one light can/can’t bridge. Optional: yesterday in a café.",
      prompts: [...scenarioFoodSkillsPrompts],
      models: [...scenarioFoodSkillsModels],
      hideModels: true,
      note: "L44 + light L47. Keep can/can’t to 1–2 questions.",
    },
    {
      type: "speakingPrompt",
      id: "l49-sc-weekend",
      kicker: "Scenario D · Free time (L32, L41–43)",
      title: "Evening / weekend past",
      description:
        "was/were + free-time story. Ask your teacher three past questions, then a 5-sentence mini story with no cards.",
      prompts: [...scenarioWeekendPastPrompts],
      models: [...scenarioWeekendPastModels],
      hideModels: true,
      note: "L32 was/were + L41–43 time story.",
    },
    {
      type: "text",
      id: "l49-exit",
      kicker: "Exit",
      title: "Now I can talk about yesterday.",
      body: "You told a real past story. That is the win — not a perfect list of irregular verbs.",
      bullets: [
        "Yesterday I got up… I had breakfast. I went…",
        "I was at work. / I worked…",
        "In the evening, I watched… / played… I went to bed…",
      ],
    },
    {
      type: "homeworkLink",
      id: "l49-hw",
      title: "Homework",
      path: "/hw-49",
      label: "HW49 →",
      summary: "6–8 sentences · voice ~45s · 5 questions",
    },
  ],
};
