import type { Lesson } from "../../../types/lesson";
import { SOUND_U5, IMG42, u5Scripts } from "../../../data/lesson42";
import {
  travelChunks,
  travelSentences,
  travelPics,
  transportVerbGroups,
  transportPhrases2a,
  travelGaps2b,
  leaveOpposite,
  timDonnaTable,
  heardQuestions3b,
  grammarDoGaps,
  doSoundPairs,
  doYouAlts,
  writeQuestions42,
} from "./activities";
import { lesson43Homework } from "./homework";
import {
  pastChunks,
  pastIrregularVerbs,
  pastModelDay,
  pastModelDayLines,
  pastReadTaskLines,
  pastRegularExampleGaps,
  pastRegularVerbs,
  pastTimeWords,
} from "./pastSimple";

function dialogLines(
  lines: readonly { who: string; text: string }[],
): string[] {
  return lines.map((l) => `${l.who}: ${l.text}`);
}

export const lesson43: Lesson = {
  id: "43",
  number: 43,
  title: "A long journey",
  level: "A1",
  moduleId: "a1-present",
  order: 43,
  status: "published",
  estimatedMinutes: 60,
  hasHomework: true,
  topic: "travel · Do you…? · leave / arrive · Past Simple preview",
  description:
    "How you travel to work: match photos, leave/arrive, Do you…?, Tim & Donna listening, speaking, and a soft Past Simple (yesterday) preview.",
  chips: [
    "by bus / train",
    "leave · arrive",
    "Do you…?",
    "yesterday · Past Simple",
  ],
  route: "/lessons/43",
  prevLessonPath: "/lesson-42",
  nextLessonPath: "/lessons",
  navLinks: [
    { label: "← Back to lessons", path: "/lessons" },
    { label: "← Lesson 42", path: "/lesson-42", ghost: true },
    { label: "HW43 →", path: "/hw-43", ghost: true },
  ],
  homework: lesson43Homework,
  flow: [
    { href: "#l43-intro", label: "Intro" },
    { href: "#l43-match", label: "1a Match" },
    { href: "#l43-audio-r4", label: "1b Listen" },
    { href: "#l43-vocab", label: "Vocab" },
    { href: "#l43-speak1c", label: "1c Speak" },
    { href: "#l43-2a", label: "2a Verbs" },
    { href: "#l43-2b", label: "2b Gaps" },
    { href: "#l43-2c", label: "2c Opposite" },
    { href: "#l43-audio-r5", label: "3a Listen" },
    { href: "#l43-table", label: "Table" },
    { href: "#l43-heard", label: "3b Tick" },
    { href: "#l43-grammar", label: "4 Do" },
    { href: "#l43-audio-r6", label: "5 Sound" },
    { href: "#l43-alts", label: "6 Alts" },
    { href: "#l43-write", label: "7a Write" },
    { href: "#l43-speak7b", label: "7b Speak" },
    { href: "#l43-past", label: "Past Simple" },
    { href: "#l43-exit", label: "Exit" },
  ],
  sections: [
    {
      type: "text",
      id: "l43-intro",
      kicker: "Travel",
      title: "A long journey",
      description: "Talk about how you travel to work / university.",
      body: "",
      bullets: travelSentences.map((s) => `${s.n}. ${s.text}`),
      note: "1a Match photos A–G with sentences 1–7 below.",
    },
    {
      type: "custom",
      id: "l43-match",
      kicker: "1a · Photos",
      title: "Match photos A–G",
      componentKey: "photo-sentence-match",
      props: {
        images: travelPics.map((p) => ({
          id: p.id,
          src: IMG42(p.file),
          alt: p.label,
          answer: String(p.answer),
        })),
        options: travelSentences.map((s) => ({
          value: String(s.n),
          label: `${s.n}. ${s.text}`,
        })),
      },
    },
    {
      type: "custom",
      id: "l43-audio-r4",
      kicker: "1b · Audio",
      title: "Listen and repeat",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(4),
        trackLabel: "R4",
        exercise: "1b",
        title: "Travel sentences · listen and repeat",
        ariaLabel: "Unit 5 track R4 — travel sentences",
        transcriptLines: [...u5Scripts[4]],
      },
    },
    {
      type: "custom",
      id: "l43-vocab",
      kicker: "Vocab",
      title: "Flip UA → English",
      description: "Tap a card. Then say the English phrase with your teacher.",
      componentKey: "vocab-flip",
      props: {
        cards: travelChunks.map((c) => ({
          front: c.ua,
          back: c.en,
          example: c.example,
          speak: c.en,
        })),
      },
    },
    {
      type: "speakingPrompt",
      id: "l43-speak1c",
      kicker: "1c · Speaking",
      title: "True for you?",
      description:
        "Which sentences in 1a are true for you? Tell your teacher.",
      prompts: travelSentences.map((s) => s.text),
      note: "Say: This is true for me. / This isn't true for me.",
    },
    {
      type: "fillBlank",
      id: "l43-2a",
      kicker: "2a · Verbs",
      title: "Complete transport phrases",
      description:
        "Complete phrases 1–3 with verb groups a–c. Use Exercise 1a to help you.",
      chips: transportVerbGroups.map((g) => `${g.id}. ${g.label}`),
      items: transportPhrases2a.map((g) => ({
        id: `p2a-${g.id}`,
        before: "",
        after: g.after,
        options: transportVerbGroups.map((o) => `${o.id}. ${o.label}`),
        correctAnswers: [`${g.answer}. ${g.answerLabel}`],
      })),
    },
    {
      type: "fillBlank",
      id: "l43-2b",
      kicker: "2b · Gaps",
      title: "Complete the sentences",
      items: travelGaps2b.map((g) => ({
        id: `g2b-${g.id}`,
        before: g.before,
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "fillBlank",
      id: "l43-2c",
      kicker: "2c · Opposite",
      title: "Opposite of leave",
      description: "Read the sentences in 2b again. What is the opposite of leave?",
      items: [
        {
          id: "opp-leave",
          before: "→",
          after: "",
          correctAnswers: [...leaveOpposite.answers],
        },
      ],
    },
    {
      type: "custom",
      id: "l43-audio-r5",
      kicker: "3a · Audio",
      title: "Donna and Tim · travel to work",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(5),
        trackLabel: "R5",
        exercise: "3a",
        title: "Donna and Tim · travel to work",
        ariaLabel: "Unit 5 track R5 — Donna and Tim",
        transcriptLines: dialogLines(u5Scripts[5]),
      },
    },
    {
      type: "fillBlank",
      id: "l43-table",
      kicker: "3a · Table",
      title: "Listen and complete the table",
      items: timDonnaTable.map((row) => ({
        id: `td-${row.id}`,
        before: `${row.who} · ${row.label}`,
        after: "",
        correctAnswers: [...row.answers],
      })),
    },
    {
      type: "custom",
      id: "l43-heard",
      kicker: "3b · Listening",
      title: "Tick the questions you hear",
      description: "Listen again. Tick only the questions from the audio.",
      componentKey: "tick-list",
      props: {
        items: heardQuestions3b.map((item) => ({
          id: String(item.id),
          label: item.q,
          correct: item.heard,
        })),
      },
    },
    {
      type: "fillBlank",
      id: "l43-grammar",
      kicker: "4 · Grammar",
      title: "Present simple questions: I / you / we / they",
      description: "Read and complete the grammar box. Use Exercise 3b to help you.",
      items: grammarDoGaps.map((g) => ({
        id: `do-${g.id}`,
        before: g.before || `(${g.id})`,
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "custom",
      id: "l43-audio-r6",
      kicker: "5 · Pronunciation",
      title: "Do / do · same or different?",
      description:
        "Listen. Do the words in blue sound the same or different? Tip: in questions Do is often weak (/də/); in answers do is strong (/duː/).",
      componentKey: "native-audio",
      props: {
        src: SOUND_U5(6),
        trackLabel: "R6",
        exercise: "5",
        title: "Do / do · same or different?",
        ariaLabel: "Unit 5 track R6 — Do pronunciation",
        transcriptLines: dialogLines(u5Scripts[6]),
      },
    },
    {
      type: "custom",
      id: "l43-sound",
      kicker: "5 · Check",
      title: "Same or different?",
      description:
        "Do the words in blue sound the same or different?",
      componentKey: "same-or-different",
      props: {
        tip: "Tip: у питанні Do часто слабке (/də/), у відповіді do — сильне (/duː/).",
        items: doSoundPairs.map((item) => ({
          id: String(item.id),
          a: item.a,
          b: item.b,
          blueA: item.blueA,
          blueB: item.blueB,
          answer: item.answer,
        })),
      },
    },
    {
      type: "fillBlank",
      id: "l43-alts",
      kicker: "6 · Grammar",
      title: "Choose the correct alternatives",
      description: "Обери правильний варіант у діалогах.",
      items: doYouAlts.map((g) => ({
        id: `alt-${g.id}`,
        before: g.before,
        after: g.after,
        options: [...g.options],
        correctAnswers: [g.answer],
      })),
    },
    {
      type: "fillBlank",
      id: "l43-write",
      kicker: "7a · Writing",
      title: "Put the words in the correct order",
      description:
        "Склади питання і напиши його сам. Example: What time do you leave home?",
      items: writeQuestions42.map((item, i) => ({
        id: `wq-${i + 1}`,
        before: `${item.scramble}`,
        after: "",
        correctAnswers: [...item.answers],
        wide: true,
      })),
    },
    {
      type: "speakingPrompt",
      id: "l43-speak7b",
      kicker: "7b · Speaking",
      title: "Ask and answer with your teacher",
      description:
        "Задай учителю питання з 7a і відповідай сам про свій шлях на роботу / університет.",
      prompts: [
        "What time do you leave home?",
        "How do you travel to work / university?",
        "What time do you arrive?",
        "Do you walk / take the bus / cycle?",
      ],
      models: [
        "I leave home at 8.00 from Monday to Friday.",
        "I go to work by bus.",
        "I arrive at about 8.45.",
        "No, I don't. I take the train.",
      ],
      note: "A: What time do you leave home? · B: I leave home at 8.00 from Monday to Friday.",
    },
    {
      type: "custom",
      id: "l43-past",
      kicker: "Preview",
      title: "Past Simple: Yesterday",
      description:
        "Ознайомлення перед наступними уроками. Сьогодні читаємо, вчимо слова і пробуємо прості речення про вчора.",
      componentKey: "tense-preview",
      props: {
        lead: "Past Simple — час про минуле. Ми говоримо про те, що вже сталося: вчора, минулої ночі, минулого тижня.",
        contrast: [
          {
            label: "Present Simple",
            example: "I work every day.",
            gloss: "зараз / зазвичай",
          },
          {
            label: "Past Simple",
            example: "I worked yesterday.",
            gloss: "вчора / у минулому",
          },
        ],
        rules: [
          {
            title: "Правильні дієслова",
            body: "Додаємо -ed.",
            example: "work → worked",
          },
          {
            title: "Неправильні дієслова",
            body: "Форму треба запам'ятати.",
            example: "go → went",
          },
          {
            title: "Часові маркери",
            body: "Слова про минуле.",
            example: "yesterday · last night · … ago",
          },
        ],
        note: "Для I / you / he / she / we / they форма Past Simple часто однакова: I worked, he worked, they worked.",
      },
    },
    {
      type: "custom",
      id: "l43-past-time",
      kicker: "Часові слова",
      title: "Yesterday · last · ago",
      description: "Tap: українською → англійською.",
      componentKey: "vocab-flip",
      props: {
        cards: pastTimeWords.map((w) => ({
          front: w.gloss,
          back: w.term,
          speak: w.term,
        })),
      },
    },
    {
      type: "text",
      id: "l43-past-regular-intro",
      kicker: "Правильні дієслова",
      title: "Add -ed",
      body: "У Past Simple додаємо -ed. Форма однакова для всіх: I worked, he worked, they worked.",
    },
    {
      type: "custom",
      id: "l43-past-regular",
      kicker: "Правильні дієслова",
      title: "Present → Past Simple",
      description: "Tap: українською → Present → Past.",
      componentKey: "vocab-flip",
      props: {
        cards: pastRegularVerbs.map(([present, past, ua]) => ({
          front: ua,
          back: `${present} → ${past}`,
          example: `I ${past}.`,
          speak: past,
        })),
      },
    },
    {
      type: "fillBlank",
      id: "l43-past-examples",
      kicker: "Приклади",
      title: "Regular verbs · examples",
      description:
        "Впиши дієслово в Past Simple (з -ed). Потім Check.",
      items: pastRegularExampleGaps.map((g) => ({
        id: g.id,
        before: g.before,
        after: g.after,
        correctAnswers: [...g.answers],
      })),
    },
    {
      type: "text",
      id: "l43-past-irregular-intro",
      kicker: "Неправильні дієслова",
      title: "No -ed — remember the form",
      body: "У цих словах не додаємо -ed: форму Past Simple треба просто запам'ятати.",
    },
    {
      type: "custom",
      id: "l43-past-irregular",
      kicker: "Неправильні дієслова",
      title: "Important irregular verbs",
      componentKey: "verb-table",
      props: {
        columns: ["Present", "Past Simple", "Українською"],
        rows: pastIrregularVerbs.map((row) => [...row]),
      },
    },
    {
      type: "custom",
      id: "l43-past-chunks",
      kicker: "Chunks",
      title: "Найважливіші фрази",
      description:
        "Tap: українською → англійською. Потім скажи фразу з учителем.",
      componentKey: "vocab-flip",
      props: {
        cards: pastChunks.map((c) => ({
          front: c.gloss,
          back: c.term,
          speak: c.term,
        })),
      },
    },
    {
      type: "text",
      id: "l43-past-model",
      kicker: "Model day",
      title: "5–7 простих речень про вчора",
      description:
        "Спочатку достатньо навчитися сказати кілька простих речень про yesterday.",
      body: "",
      bullets: [...pastModelDayLines],
    },
    {
      type: "text",
      id: "l43-past-read",
      kicker: "Before next lesson",
      title: "Маленьке завдання",
      description:
        "Лише прочитай і спробуй зрозуміти текст. Не перекладай кожне слово.",
      body: "",
      bullets: [...pastReadTaskLines],
      note: "Ask your teacher: What did you understand?",
    },
    {
      type: "speakingPrompt",
      id: "l43-past-speak",
      kicker: "Speaking · soft",
      title: "Say 3–5 sentences about yesterday",
      description:
        "Скажи вчителю 3–5 простих речень. Можна використати chunks зверху.",
      prompts: [
        "Yesterday I got up at …",
        "I had breakfast / drank coffee / tea.",
        "I went to work / stayed at home.",
        "In the evening I …",
        "I went to bed early / late.",
      ],
      note: pastModelDay,
    },
    {
      type: "text",
      id: "l43-exit",
      kicker: "Exit check",
      title: "Can you…?",
      body: "",
      bullets: [
        "Say how you travel: I go by bus. I cycle to work.",
        "Ask: How do you travel…? What time do you leave / arrive?",
        "Answer: Yes, I do. / No, I don't.",
        "Preview: say 3 sentences about yesterday (I got up… I went… I watched…).",
      ],
    },
    {
      type: "homeworkLink",
      id: "l43-hw",
      kicker: "Homework",
      title: "HW43",
      path: "/hw-43",
      label: "HW43 →",
      summary: "Travel phrases, gaps, and transport chunks.",
    },
  ],
};
